#!/system/bin/sh
show_banner() {
    echo "======================================="
    echo "Module Truy Ân 80 Năm Quốc Khánh 2/9/1945🇻🇳"
    echo "Support: Anroid "
    echo "======================================="
    sleep 1
}

# Function to display device information
show_device_info() {
    echo "      [ DEVICE INFORMATION ]"
    echo "[Brand]   : $(getprop ro.product.brand)"
    echo "[CPU]     : $(getprop ro.hardware)"
    echo "[Android] : $(getprop ro.build.version.release)"
    echo "[Kernel]  : $(uname -r)"
    echo "[Build]   : $(getprop ro.build.display.id)"
    echo "[Time]    : $(date +%Y-%m-%d\ %H:%M:%S)"
    echo "======================================="
    sleep 1
}
suppress_logs() {
    disable_log=(
        "log.tag.AF::MmapTrack SUPPRESS"
        "log.tag.AF::OutputTrack SUPPRESS"
        "log.tag.AF::PatchRecord SUPPRESS"
        "log.tag.AF::PatchTrack SUPPRESS"
        "log.tag.AF::RecordHandle SUPPRESS"
        "log.tag.AF::RecordTrack SUPPRESS"
        "log.tag.AF::Track SUPPRESS"
        "log.tag.AF::TrackBase SUPPRESS"
        "log.tag.AF::TrackHandle SUPPRESS"
        "log.tag.APM-KpiMonitor SUPPRESS"
        "log.tag.APM-ServiceJ SUPPRESS"
        "log.tag.APM-SessionJ SUPPRESS"
        "log.tag.APM-SessionN SUPPRESS"
        "log.tag.APM-Subscriber SUPPRESS"
        "log.tag.APM::AudioCollections SUPPRESS"
        "log.tag.APM::AudioInputDescriptor SUPPRESS"
        "log.tag.APM::AudioOutputDescriptor SUPPRESS"
        "log.tag.APM::AudioPatch SUPPRESS"
        "log.tag.APM::AudioPolicyEngine SUPPRESS"
        "log.tag.APM::Devices SUPPRESS"
        "log.tag.APM::IOProfile SUPPRESS"
        "log.tag.APM::Serializer SUPPRESS"
        "log.tag.APM::VolumeCurve SUPPRESS"
        "log.tag.APM_AudioPolicyManager SUPPRESS"
        "log.tag.APM_ClientDescriptor SUPPRESS"
        "log.tag.AT SUPPRESS"
        "log.tag.AccountManager SUPPRESS"
        "log.tag.ActivityManager SUPPRESS"
        "log.tag.ActivityManagerService SUPPRESS"
        "log.tag.ActivityTaskManager SUPPRESS"
        "log.tag.AdnRecord SUPPRESS"
        "log.tag.AdnRecordCache SUPPRESS"
        "log.tag.AdnRecordLoader SUPPRESS"
        "log.tag.AlarmManager SUPPRESS"
        "log.tag.AlarmManagerService SUPPRESS"
        "log.tag.AndroidRuntime SUPPRESS"
        "log.tag.AppOps SUPPRESS"
        "log.tag.AudioAttributes SUPPRESS"
        "log.tag.AudioEffect SUPPRESS"
        "log.tag.AudioFlinger SUPPRESS"
        "log.tag.AudioFlinger::DeviceEffectProxy SUPPRESS"
        "log.tag.AudioFlinger::EffectChain SUPPRESS"
        "log.tag.AudioFlinger::EffectModule SUPPRESS"
        "log.tag.AudioHwDevice SUPPRESS"
        "log.tag.AudioManager SUPPRESS"
        "log.tag.AudioPolicy SUPPRESS"
        "log.tag.AudioPolicyManager SUPPRESS"
        "log.tag.AudioRecord SUPPRESS"
        "log.tag.AudioService SUPPRESS"
        "log.tag.AudioSystem SUPPRESS"
        "log.tag.AudioTrack SUPPRESS"
        "log.tag.BackupManager SUPPRESS"
        "log.tag.BatteryManager SUPPRESS"
        "log.tag.BatteryStatsService SUPPRESS"
        "log.tag.BluetoothAdapter SUPPRESS"
        "log.tag.BluetoothDevice SUPPRESS"
        "log.tag.BluetoothGattService SUPPRESS"
        "log.tag.BluetoothManager SUPPRESS"
        "log.tag.BluetoothService SUPPRESS"
        "log.tag.BufferQueueProducer SUPPRESS"
        "log.tag.CAM2PORT_ SUPPRESS"
        "log.tag.ClipboardManager SUPPRESS"
        "log.tag.ConnectivityManager SUPPRESS"
        "log.tag.ConnectivityService SUPPRESS"
        "log.tag.ConsumerIrService SUPPRESS"
        "log.tag.ContentManager SUPPRESS"
        "log.tag.CountryDetector SUPPRESS"
        "log.tag.DeviceIdleController SUPPRESS"
        "log.tag.DevicePolicyManager SUPPRESS"
        "log.tag.DisplayManager SUPPRESS"
        "log.tag.DisplayManagerService SUPPRESS"
        "log.tag.DockObserver SUPPRESS"
        "log.tag.DownloadManager SUPPRESS"
        "log.tag.FastCapture SUPPRESS"
        "log.tag.FastMixer SUPPRESS"
        "log.tag.FastThread SUPPRESS"
        "log.tag.FragmentManager SUPPRESS"
        "log.tag.FuseDaemon SUPPRESS"
        "log.tag.GAv4 SUPPRESS"
        "log.tag.GraphicsStats SUPPRESS"
        "log.tag.GsmCdmaConn SUPPRESS"
        "log.tag.GsmCdmaPhone SUPPRESS"
        "log.tag.HardwarePropertiesManager SUPPRESS"
        "log.tag.HardwareService SUPPRESS"
        "log.tag.IAudioFlinger SUPPRESS"
        "log.tag.IccCardProxy SUPPRESS"
        "log.tag.IccPhoneBookIM SUPPRESS"
        "log.tag.IccProvider SUPPRESS"
        "log.tag.ImsApp SUPPRESS"
        "log.tag.ImsCall SUPPRESS"
        "log.tag.ImsManager SUPPRESS"
        "log.tag.ImsPhone SUPPRESS"
        "log.tag.ImsService SUPPRESS"
        "log.tag.InputDispatcher SUPPRESS"
        "log.tag.InputManager SUPPRESS"
        "log.tag.InputMethodManager SUPPRESS"
        "log.tag.JobScheduler SUPPRESS"
        "log.tag.KeyguardManager SUPPRESS"
        "log.tag.LocationManager SUPPRESS"
        "log.tag.LocationManagerService SUPPRESS"
        "log.tag.MediaPlayer SUPPRESS"
        "log.tag.MediaPlayerService SUPPRESS"
        "log.tag.MediaRouter SUPPRESS"
        "log.tag.MediaSession SUPPRESS"
        "log.tag.MountService SUPPRESS"
        "log.tag.NetworkManagement SUPPRESS"
        "log.tag.NetworkManagementService SUPPRESS"
        "log.tag.NetworkPolicy SUPPRESS"
        "log.tag.NetworkStats SUPPRESS"
        "log.tag.NetworkTimeUpdateService SUPPRESS"
        "log.tag.NotificationManager SUPPRESS"
        "log.tag.NotificationManagerService SUPPRESS"
        "log.tag.PackageInstaller SUPPRESS"
        "log.tag.PackageManager SUPPRESS"
        "log.tag.Phone SUPPRESS"
        "log.tag.PhoneFactory SUPPRESS"
        "log.tag.PowerManager SUPPRESS"
        "log.tag.PowerManagerService SUPPRESS"
        "log.tag.PrintManager SUPPRESS"
        "log.tag.ProcessStats SUPPRESS"
        "log.tag.RIL SUPPRESS"
        "log.tag.RILC SUPPRESS"
        "log.tag.RadioManager SUPPRESS"
        "log.tag.SensorManager SUPPRESS"
        "log.tag.ServiceManager SUPPRESS"
        "log.tag.SIMRecords SUPPRESS"
        "log.tag.SQLiteQueryBuilder SUPPRESS"
        "log.tag.StatusBarManagerService SUPPRESS"
        "log.tag.StorageManager SUPPRESS"
        "log.tag.SurfaceFlinger SUPPRESS"
        "log.tag.SystemServer SUPPRESS"
        "log.tag.Telecom SUPPRESS"
        "log.tag.TelephonyManager SUPPRESS"
        "log.tag.TelephonyRegistry SUPPRESS"
        "log.tag.ThermalManager SUPPRESS"
        "log.tag.UiccCard SUPPRESS"
        "log.tag.UiccController SUPPRESS"
        "log.tag.UsbHostManager SUPPRESS"
        "log.tag.UsbManager SUPPRESS"
        "log.tag.VibratorService SUPPRESS"
        "log.tag.VpnManager SUPPRESS"
        "log.tag.WallpaperManager SUPPRESS"
        "log.tag.WifiManager SUPPRESS"
        "log.tag.WindowManager SUPPRESS"
        "log.tag.WindowManagerService SUPPRESS"
        "log.tag.MtkIccCardProxy SUPPRESS"
        "log.tag.MtkIccProvider SUPPRESS"
        "log.tag.MtkImsManager SUPPRESS"
        "log.tag.MtkImsService SUPPRESS"
        "log.tag.MtkPhoneNotifr SUPPRESS"
        "log.tag.MtkPhoneNumberUtils SUPPRESS"
        "log.tag.MtkSIMRecords SUPPRESS"
        "log.tag.MtkSmsManager SUPPRESS"
        "log.tag.MtkTelephonyManagerEx SUPPRESS"
        "log.tag.MtkUiccCard SUPPRESS"
        "log.tag.RfxAction SUPPRESS"
        "log.tag.RfxController SUPPRESS"
        "log.tag.RfxMessage SUPPRESS"
        "log.tag.RfxRilAdapter SUPPRESS"
        "log.tag.RmmDcEvent SUPPRESS"
        "log.tag.RmmNwHdlr SUPPRESS"
        "log.tag.RmmOemHandler SUPPRESS"
        "log.tag.RmmPhbReq SUPPRESS"
        "log.tag.RmmSimCommReq SUPPRESS"
        "log.tag.MtkFactory SUPPRESS"
        "log.tag.MtkEmbmsAdaptor SUPPRESS"
        "log.tag.MtkSubCtrl SUPPRESS"
        "log.tag.MtkSpnOverride SUPPRESS"
        "log.tag.MtkCsimFH SUPPRESS"
        "log.tag.MtkRuimFH SUPPRESS"
        "log.tag.MtkUsimFH SUPPRESS"
        "log.tag.MtkIsimFH SUPPRESS"
        "log.tag.MtkPhoneSwitcher SUPPRESS"
        "log.tag.MtkRecordLoader SUPPRESS"
        "log.tag.RmmWp SUPPRESS"
        "log.tag.RtmIms SUPPRESS"
        "log.tag.RtmPhb SUPPRESS"
        "log.tag.RtmNwCtrl SUPPRESS"
        "log.tag.RtmModeCont SUPPRESS"
        "log.tag.RtmRadioCont SUPPRESS"
        "log.tag.RtmEccNumberController SUPPRESS"
        "log.tag.MtkUiccCtrl SUPPRESS"
        "log.tag.MtkUiccCardApp SUPPRESS"
        "log.tag.MtkSmsMessage SUPPRESS"
        "log.tag.MtkSmsCbHeader SUPPRESS"
        "log.tag.MtkAdnRecord SUPPRESS"
        "log.tag.MtkUsimPhoneBookManager SUPPRESS"
        "log.tag.MwiRIL SUPPRESS"
        "log.tag.RmmEccNumberReqHdlr SUPPRESS"
        "log.tag.RmmImsCtlReqHdl SUPPRESS"
        "log.tag.RmmNwRatSwHdlr SUPPRESS"
        "log.tag.RmmNwUrcHdlr SUPPRESS"
        "log.tag.RmmSimBaseHandler SUPPRESS"
        "log.tag.RmmCommSimOpReq SUPPRESS"
        "log.tag.RtmEmbmsUtil SUPPRESS"
        "log.tag.RtmImsConfigController SUPPRESS"
        "log.tag.RtmImsConference SUPPRESS"
        "log.tag.RtmImsDialog SUPPRESS"
        "log.tag.RfxDisThread SUPPRESS"
        "log.tag.RfxMclMessenger SUPPRESS"
        "log.tag.RfxStatusMgr SUPPRESS"
        "log.tag.RilClient SUPPRESS"
        "log.tag.RilOpProxy SUPPRESS"
        "log.tag.MTK_APPList SUPPRESS"
        "log.tag.MTKSST SUPPRESS"
        "log.tag.MtkIccPHBIM SUPPRESS"
        "log.tag.MtkIccSmsInterfaceManager SUPPRESS"
        "log.tag.RfxRilUtils SUPPRESS"
        "log.tag.RfxOpUtils SUPPRESS"
        "log.tag.RfxMainThread SUPPRESS"
        "log.tag.RfxHandlerMgr SUPPRESS"
        "log.tag.RfxContFactory SUPPRESS"
        )
        for commands in "${disable_log[@]}"; do
    IFS=' ' read -r name value <<< "$commands"
    setprop "$name" "$value"
done
}

apply_settings() {
    settings_type="$1"
    shift
    settings=("$@")

    for setting in "${settings[@]}"; do
        key="${setting%=*}"
        value="${setting#*=}"
        current_value=$(settings get "$settings_type" "$key" 2>/dev/null)

        # Chỉ set khi khác để tránh log spam
        if [ "$current_value" != "$value" ]; then
            settings put "$settings_type" "$key" "$value" >/dev/null 2>&1
        fi
    done
}
secure_settings=(
"accessibility_allow_diagonal_scrolling=0"
"accessibility_button_mode=0"
"accessibility_change_magnification_size=0"
"accessibility_display_magnification_enabled=0"
"accessibility_display_magnification_scale=1.0"
"accessibility_enabled=1"
"accessibility_magnification_activated=0"
"accessibility_magnification_capability=0"
"accessibility_magnification_mode=0"
"accessibility_shortcut_target_service="
"adaptive_sleep=0"
"allowed_geolocation_origins="
"android_id=1234567890"
"autofill_field_classification=0"
"autofill_service="
"autofill_service_search_uri="
"aware_enabled=0"
"aware_lock_enabled=0"
"backup_enabled=0"
"badge_app_icon_type=0"
"biometrics_strong_enroll_timestamp=0"
"bluetooth_settings_foreground=0"
"bluetooth_settings_foreground_qp=0"
"charging_sounds_enabled=0"
"charging_vibration_enabled=0"
"clipboard_show_access_notifications=0"
"color_adjustment_type=0"
"display_density_forced=420"
"double_tap_to_wake=0"
"edge_enable=0"
"edge_handle_size_percent=20"
"edge_handle_transparency=100"
"emergency_gesture_enabled=0"
"enabled_accessibility_services="
"enabled_input_methods="
"enabled_notification_listeners="
"face_brighten_screen=0"
"face_stay_on_lock_screen=0"
"fingerprint_always_on=0"
"fingerprint_screen_lock=1"
"game_auto_temperature_control=1"
"game_double_swipe_enable=0"
"game_touchscreen_lock=0"
"gamesdk_version=1"
"immersive_mode_confirmations=confirmed"
"incall_power_button_behavior=1"
"install_non_market_apps=1"
"location_mode=3"
"lock_screen_allow_private_notifications=0"
"lock_screen_show_notifications=0"
"lock_screen_show_only_unseen_notifications=0"
"lock_screen_lock_after_timeout=3000"
"lockscreen.disabled=0"
"long_press_timeout=200"
"multi_press_timeout=200"
"navigation_mode=2"
"nfc_payment_foreground=0"
"notification_badging=0"
"notification_bubbles=0"
"one_handed_mode_enabled=0"
"power_menu_locked_show_content=0"
"refresh_rate_mode=0"
"screen_extra_brightness=1"
"selected_input_method_subtype=0"
"silence_gesture=0"
"skip_gesture=0"
"sleep_timeout=600000"
"smart_tethering_db_ver=1"
"spatial_audio_enabled=0"
"status_bar_show_vibrate_icon=0"
"swipe_bottom_to_notification_enabled=1"
"sysui_tuner_version=1"
"touch_exploration_enabled=0"
"ui_night_mode=1"
"user_setup_complete=1"
"wake_gesture_enabled=0"
"wifi_saved_state=1"
"zen_duration=0"
)

global_settings=(
"airplane_mode_on=0"
"always_finish_activities=0"
"animator_duration_scale=0.5"
"transition_animation_scale=0.5"
"window_animation_scale=0.5"
"Contacts_move_simcontacts_not_now=0"
"Phenotype_boot_count=0"
"Phenotype_flags=0"
"_boot_Phenotype_flags=0"
"activity_starts_logging_enabled=0"
"add_users_when_locked=0"
"airplane_mode_on=0"
"airplane_mode_radios=cell,bluetooth,wifi,nfc"
"airplane_mode_toggleable_radios=wifi"
"alarm_manager_constants="
"alarm_manager_dummy_flags=0"
"alt_bypass_wifi_requirement_time_millis=0"
"always_on_display_constants="
"ambient_enabled=0"
"ambient_force_when_docked=0"
"ambient_low_bit_enabled=0"
"ambient_low_bit_enabled_dev=0"
"ambient_plugged_timeout_min=0"
"ambient_tilt_to_bright=0"
"ambient_tilt_to_wake=0"
"ambient_touch_to_wake=0"
"android_wear_system_edition=0"
"android_wear_version=0"
"anomaly_config="
"anomaly_config_version=0"
"anomaly_detection_constants="
"apm_enhancement_enabled=0"
"app_idle_constants="
"app_standby_enabled=0"
"appwidget_prevent_remove_all=0"
"assisted_gps_enabled=1"
"audio_safe_volume_state=2"
"auto_brightness_limit=0"
"auto_time=1"
"auto_time_zone=1"
"auto_wifi=0"
"backup_agent_timeout_parameters="
"backup_network_mode=0"
"battery_protection_threshold=85"
"battery_stats_constants="
"battery_tip_constants="
"bluetooth_on=0"
"boot_count=1"
"bug_report=0"
"burn_in_protection=0"
"call_auto_retry=0"
"car_dock_sound=0"
"car_undock_sound=0"
"cdma_cell_broadcast_sms=0"
"cell_on=1"
"charging_started_sound=0"
"clockwork_24hr_time=1"
"data_roaming=0"
"debug_app="
"default_device_name=Android"
"default_install_location=0"
"default_restrict_background_data=0"
"development_settings_enabled=0"
"device_name=Android"
"device_provisioned=1"
"display_size_forced=0"
"do_setup_complete=1"
"dock_audio_media_enabled=0"
"dock_sounds_enabled=0"
"emergency_tone=0"
"enable_cellular_on_boot=1"
"enable_non_resizable_multi_window=0"
"font_size=1.0"
"force_peak_refresh_rate=0"
"force_resizable_activities=0"
"freeform_handler_help_popup_count=0"
"gnss_satellite_blocklist="
"has_pay_tokens=0"
"heads_up_notifications_enabled=1"
"hidden_api_policy=1"
"hotword_detection_enabled=0"
"job_scheduler_constants="
"key_sleep_charging=0"
"lid_behavior=0"
"limit_brightness_state=0"
"location_background_throttle_interval_ms=1800000"
"lock_sound=0"
"low_battery_sound=0"
"low_power=0"
"low_power_sticky=0"
"master_sync_status=1"
"mobile_data=1"
"mobile_data_always_on=0"
"multi_window_menu_in_full_screen=0"
"navigation_bar_gesture_hint=1"
"network_avoid_bad_wifi=1"
"network_recommendations_enabled=1"
"network_watchlist_enabled=1"
"night_display_forced_auto_mode_available=0"
"notification_snooze_options=0"
"open_in_split_screen_view=0"
"power_button_long_press=1"
"power_sounds_enabled=0"
"preferred_network_mode=9"
"protect_battery=0"
"quick_start_flow_type=0"
"ram_expand_size=0"
"restricted_device_performance=0"
"screen_off_timeout=30000"
"stay_on_while_plugged_in=0"
"sysui_demo_allowed=0"
"transition_animation_scale=1.0"
"unlock_sound=0"
"usb_mass_storage_enabled=0"
"uwb_enabled=0"
"verifier_timeout=0"
"wifi_display_on=0"
"wifi_networks_available_notification_on=0"
"wifi_on=1"
"wifi_scan_always_enabled=1"
"wifi_sleep_policy=2"
"wifi_wakeup_enabled=0"
"wifi_watchdog_poor_network_test_enabled=0"
"window_animation_scale=1.0"
"zen_mode=0"
"zram_enabled=1"
)
system_settings=(
"screen_brightness=180"
"screen_off_timeout=60000"
"pointer_speed=7"
"touch_slop=1"
"SEM_VIBRATION_FORCE_TOUCH_INTENSITY=2"
"SEM_VIBRATION_NOTIFICATION_INTENSITY=2"
"SMLDM_BEARER=0"
"SOFTWARE_UPDATE_LAST_CHECKED_DATE=0"
"SOFTWARE_UPDATE_WIFI_ONLY2=1"
"SOUNDALIVE_AUDIO_PATH=0"
"VIB_FEEDBACK_MAGNITUDE=2"
"VIB_RECVCALL_MAGNITUDE=2"
"accelerometer_rotation=1"
"adaptive_fast_charging=1"
"alarm_alert=content://settings/system/alarm_alert"
"all_sound_off=0"
"android.contacts.DISPLAY_ORDER=1"
"android.contacts.SORT_ORDER=1"
"android.wallpaper.settings_systemui_transparency=0"
"apply_ramping_ringer=0"
"assistant_menu=0"
"auto_adjust_touch=1"
"auto_screen_on=0"
"automatic_unlock=1"
"badge_for_dm_battery=0"
"badge_for_fota=0"
"block_unwanted_call=0"
"blue_light_filter=0"
"blue_light_filter_opacity=0"
"blue_light_filter_type=0"
"call_answer_vib=1"
"call_conn_tone=1"
"call_end_tone=0"
"call_end_vib=0"
"call_extra_volume=0"
"call_noise_reduction=1"
"charging_info_always=0"
"custom_wallpaper_color_areas_lock=0"
"default_vibration_pattern=0"
"dim_screen=0"
"display_night_theme=0"
"double_tab_to_wake_up=1"
"double_tap_to_sleep=0"
"dtmf_tone=1"
"edge_lighting=0"
"enable_smart_capture=1"
"end_button_behavior=2"
"font_scale=1.0"
"haptic_feedback_enabled=1"
"lift_to_wake=1"
"lockscreen_sounds_enabled=0"
"master_motion=1"
"media_vibration_intensity=2"
"motion_engine=1"
"motion_overturn=1"
"motion_pick_up=1"
"mute_streams_affected=0"
"navigation_gestures_vibrate=1"
"nearby_scanning_enabled=0"
"notification_light_pulse=0"
"notification_sound=content://settings/system/notification_sound"
"notification_vibration_sep_index=0"
"pointer_speed=0"
"proximity_sensor=1"
"quickshare_enabled=0"
"rcs_user_setting=0"
"record_calls_automatically_on_off=0"
"remove_animations=0"
"ringtone=content://settings/system/ringtone"
"ringtone_vibration_sep_index=0"
"samsung_errorlog_agree=0"
"screen_brightness=120"
"screen_brightness_mode=1"
"screen_mode_setting=0"
"screen_off_timeout=30000"
"show_notification_app_icon=1"
"smart_capture_screenshot_format=0"
"sound_effects_enabled=1"
"status_bar_show_date=0"
"super_fast_charging=1"
"surface_palm_swipe=0"
"sync_vibration_with_notification=1"
"sync_vibration_with_ringtone=1"
"system_locales=en-US"
"user_rotation=0"
"vibrate_when_ringing=1"
"volume_alarm=7"
"volume_music=8"
"volume_notification=5"
"volume_ring=5"
"volume_system=5"
"wallpaper_finish_drawing=0"
"wireless_fast_charging=1"
)
apply_settings secure "${secure_settings[@]}"
apply_settings global "${global_settings[@]}"
apply_settings system "${system_settings[@]}"
kyser() {
cmd thermalservice override-status 0
setprop debug.hwui.renderer "$renderer"
setprop debug.renderengine.backend skiagputhreaded
setprop debug.sf.use_phase_offsets_as_durations true
}
show_banner
show_device_info
kyser
suppress_logs
echo "====================================================="
echo "   [ DISABLING USB DEBUGGING ]"
echo "   [ DISABLING WIFI DEBUGGING ]"
echo "   [ REDUCING SYSTEM LOGS ]"
echo "   [ REDUCING ANIMATION SCALE ]"
echo "   [ INCREASING TOUCH RESPONSE ]"
echo "   [ DISABLING BACKGROUND SCANNING ]"
echo "   [ OPTIMIZING REFRESH RATE ]"
echo "   [ REDUCING HAPTIC FEEDBACK ]"
echo "   [ DISABLING UNUSED SYSTEM FEATURES ]"
echo "   [ BOOSTING PERFORMANCE MODE ]"
echo "   [ SUPER CAP IMAGE SENSITIVITY INCREASE ]"
echo "====================================================="
echo ">>> Đang lấy độ phân giải hiện tại..."
size=$(wm size | grep -o '[0-9]*x[0-9]*')
width=$(echo $size | cut -d'x' -f1)
height=$(echo $size | cut -d'x' -f2)
echo ">>> Kích thước gốc: ${width}x${height}"

# Nhân lên 1.9 lần và làm tròn
new_width=$(echo "$width * 1.9" | bc | cut -d'.' -f1)
new_height=$(echo "$height * 1.9" | bc | cut -d'.' -f1)

echo ">>>  Nhân độ phân giải lên 1.9 lần..."
echo ">>>  Kích thước mới: ${new_width}x${new_height}"

wm size ${new_width}x${new_height}
echo ">>>  Đã áp dụng độ phân giải mới!"
echo "Dùng 'wm size reset' để khôi phục mặc định."