#!/system/bin/sh

log_file="/data/local/tmp/sensi_plusx_v3_log.txt"
now=$(date '+%Y-%m-%d %H:%M:%S')

print_progress() {
    local msg=$1
    echo "[*] $msg..."
    for i in {1..5}; do
        echo -n "█"
        sleep 0.1
    done
    echo " Done!"
}

print_banner() {
    clear
    echo "╔══════════════════════════════════════════════════════════════╗"
    echo "║          Sensi PlusX V3 by Kysertweaks                       ║"
    echo "╠═══════════════════════════════════════════════════════╦════╩╗"
    echo "║  ███████╗███████╗███╗   ██╗███████╗██╗    ██╗██╗██╗   ██║ ║"
    echo "║  ██╔════╝██╔════╝████╗  ██║██╔════╝██║    ██║██║██║   ██║ ║"
    echo "║  ███████╗█████╗  ██╔██╗ ██║█████╗  ██║ █╗ ██║██║██║   ██║ ║"
    echo "║  ╚════██║██╔══╝  ██║╚██╗██║██╔══╝  ██║███╗██║██║██║   ██║ ║"
    echo "║  ███████║███████╗██║ ╚████║██║     ╚███╔███╔╝██║╚██████╔╝ ║"
    echo "╠═════════════════════╦═════════════════════════════════╩═════╩╗"
    echo "║ Power Features:     ║ Ultra Touch Sensitivity                ║"
    echo "║ - Super Light Aim   ║ Graphics Boost                         ║"
    echo "║ - Smooth Recoil     ║ Headshot Optimizer (Red Dot)           ║"
    echo "║ - Max Performance   ║ Log Suppression (540 tags)             ║"
    echo "╠═════════════════════╩═════════════════════════════════════════╩╗"
    echo "║ © Copyright 2025 by Kysertweaks                               ║"
    echo "║ Date: $now                                                  ║"
    echo "║ Country: VietNam 🇻🇳                                         ║"
    echo "║ PID: $$ | UID: $(id -u)                                     ║"
    echo "╚══════════════════════════════════════════════════════════════╝"
}

check_compatibility() {
    print_progress "Checking System Compatibility"
    refresh_rate=$(dumpsys SurfaceFlinger | grep "refresh-rate" | awk '{print $3}' | head -1)
    [ -z "$refresh_rate" ] && refresh_rate=60
    vulkan_support=$(getprop ro.hardware.vulkan)
    [ -z "$vulkan_support" ] && vulkan_support="unknown"
    echo "[*] Refresh Rate: ${refresh_rate}Hz | Vulkan: $vulkan_support" >> "$log_file"
    echo "[+] Compatibility Check Passed"
}

log() {
    print_progress "Applying Log Suppression (540 tags)"
    log_tags=(
        "log.tag.ActivityManager WARN"
        "log.tag.ActivityRecognition WARN"
        "log.tag.ActivityService WARN"
        "log.tag.ActivityStackSupervisor WARN"
        "log.tag.ActivityTrigger WARN"
        "log.tag.AnrManager WARN"
        "log.tag.AppCompat WARN"
        "log.tag.AppComponent WARN"
        "log.tag.AppControl WARN"
        "log.tag.AppCore WARN"
        "log.tag.AppEngine WARN"
        "log.tag.AppFramework WARN"
        "log.tag.AppHandler WARN"
        "log.tag.AppIdleHistory WARN"
        "log.tag.AppModule WARN"
        "log.tag.AppOps WARN"
        "log.tag.AppPrediction WARN"
        "log.tag.AppPredictionManager WARN"
        "log.tag.AppPredictionService WARN"
        "log.tag.AppStandby WARN"
        "log.tag.AppStandbyBucket WARN"
        "log.tag.AppStandbyController WARN"
        "log.tag.AppStandbyManager WARN"
        "log.tag.AppStandbyState WARN"
        "log.tag.AppStandbyTracker WARN"
        "log.tag.AppSystem WARN"
        "log.tag.AppTimeLimitController WARN"
        "log.tag.AppWidgetControl WARN"
        "log.tag.AppWidgetControlService WARN"
        "log.tag.AppWidgetManager WARN"
        "log.tag.AppWidgetManagerControl WARN"
        "log.tag.AppWidgetManagerService WARN"
        "log.tag.AppWidgetService WARN"
        "log.tag.AppWidgetServiceControl WARN"
        "log.tag.ArtManagerService WARN"
        "log.tag.AudioComponent WARN"
        "log.tag.AudioControl WARN"
        "log.tag.AudioControlManager WARN"
        "log.tag.AudioControlService WARN"
        "log.tag.AudioCore WARN"
        "log.tag.AudioEngine WARN"
        "log.tag.AudioFocus WARN"
        "log.tag.AudioFramework WARN"
        "log.tag.AudioHandler WARN"
        "log.tag.AudioManager WARN"
        "log.tag.AudioManagerControl WARN"
        "log.tag.AudioManagerService WARN"
        "log.tag.AudioModule WARN"
        "log.tag.AudioPolicy WARN"
        "log.tag.AudioService WARN"
        "log.tag.AudioServiceControl WARN"
        "log.tag.AudioStack WARN"
        "log.tag.AudioSystem WARN"
        "log.tag.AutoRun WARN"
        "log.tag.BackupManager WARN"
        "log.tag.BatteryHealthService WARN"
        "log.tag.BatteryMonitor WARN"
        "log.tag.BatterySaver WARN"
        "log.tag.BatterySaverController WARN"
        "log.tag.BatterySaverPolicy WARN"
        "log.tag.BatterySaverSchedule WARN"
        "log.tag.BatterySaverStateMachine WARN"
        "log.tag.BatteryService WARN"
        "log.tag.BatteryStats WARN"
        "log.tag.BatteryStatsHelper WARN"
        "log.tag.BatteryStatsValidator WARN"
        "log.tag.BatteryUsageStats WARN"
        "log.tag.Binder WARN"
        "log.tag.BinderCleaner WARN"
        "log.tag.BluetoothA2dp WARN"
        "log.tag.BluetoothAdapter WARN"
        "log.tag.BluetoothAudio WARN"
        "log.tag.BluetoothAvrcp WARN"
        "log.tag.BluetoothAvrcpService WARN"
        "log.tag.BluetoothBroadcast WARN"
        "log.tag.BluetoothCall WARN"
        "log.tag.BluetoothCodec WARN"
        "log.tag.BluetoothComponent WARN"
        "log.tag.BluetoothControlManager WARN"
        "log.tag.BluetoothControlService WARN"
        "log.tag.BluetoothCore WARN"
        "log.tag.BluetoothEngine WARN"
        "log.tag.BluetoothFramework WARN"
        "log.tag.BluetoothHandler WARN"
        "log.tag.BluetoothHeadset WARN"
        "log.tag.BluetoothHealth WARN"
        "log.tag.BluetoothLe WARN"
        "log.tag.BluetoothLeAdvertiser WARN"
        "log.tag.BluetoothLeAudio WARN"
        "log.tag.BluetoothLeAudioBroadcast WARN"
        "log.tag.BluetoothLeAudioCodec WARN"
        "log.tag.BluetoothLeAudioProfile WARN"
        "log.tag.BluetoothLeBroadcast WARN"
        "log.tag.BluetoothLeCallControl WARN"
        "log.tag.BluetoothLeScanner WARN"
        "log.tag.BluetoothManager WARN"
        "log.tag.BluetoothManagerControl WARN"
        "log.tag.BluetoothManagerService WARN"
        "log.tag.BluetoothManagerServiceControl WARN"
        "log.tag.BluetoothMap WARN"
        "log.tag.BluetoothModule WARN"
        "log.tag.BluetoothPbap WARN"
        "log.tag.BluetoothProfile WARN"
        "log.tag.BluetoothProfileAudio WARN"
        "log.tag.BluetoothProfileService WARN"
        "log.tag.BluetoothService WARN"
        "log.tag.BluetoothServiceControl WARN"
        "log.tag.BluetoothStack WARN"
        "log.tag.BluetoothSystem WARN"
        "log.tag.BroadcastManager WARN"
        "log.tag.BroadcastQueue WARN"
        "log.tag.BroadcastRadio WARN"
        "log.tag.BroadcastStats WARN"
        "log.tag.BugreportManager WARN"
        "log.tag.CachedAppOptimizer WARN"
        "log.tag.CachedDeviceState WARN"
        "log.tag.CameraDevice WARN"
        "log.tag.CameraManager WARN"
        "log.tag.CameraService WARN"
        "log.tag.CarrierConfig WARN"
        "log.tag.CarrierConfigLoader WARN"
        "log.tag.CarrierIdentifier WARN"
        "log.tag.CdmaBroadcast WARN"
        "log.tag.CdmaCallOptions WARN"
        "log.tag.CdmaCallTracker WARN"
        "log.tag.CdmaConnection WARN"
        "log.tag.CdmaHandler WARN"
        "log.tag.CdmaInboundSmsHandler WARN"
        "log.tag.CdmaProvider WARN"
        "log.tag.CdmaService WARN"
        "log.tag.CdmaServiceCategory WARN"
        "log.tag.CdmaServiceProvider WARN"
        "log.tag.CdmaServiceStateTracker WARN"
        "log.tag.CdmaSmsBroadcast WARN"
        "log.tag.CellBroadcastService WARN"
        "log.tag.ClientLifecycleManager WARN"
        "log.tag.ClipboardManager WARN"
        "log.tag.ClipboardService WARN"
        "log.tag.CompanionComponent WARN"
        "log.tag.CompanionControl WARN"
        "log.tag.CompanionControlService WARN"
        "log.tag.CompanionCore WARN"
        "log.tag.CompanionDeviceManager WARN"
        "log.tag.CompanionDeviceService WARN"
        "log.tag.CompanionEngine WARN"
        "log.tag.CompanionFramework WARN"
        "log.tag.CompanionHandler WARN"
        "log.tag.CompanionManager WARN"
        "log.tag.CompanionManagerControl WARN"
        "log.tag.CompanionManagerService WARN"
        "log.tag.CompanionModule WARN"
        "log.tag.CompanionStack WARN"
        "log.tag.CompanionSystem WARN"
        "log.tag.CompatChanges WARN"
        "log.tag.CompatConfig WARN"
        "log.tag.CompatibilityChangeReporter WARN"
        "log.tag.ConnectivityControl WARN"
        "log.tag.ConnectivityControlService WARN"
        "log.tag.ConnectivityDiagnostics WARN"
        "log.tag.ConnectivityManager WARN"
        "log.tag.ConnectivityMetricsLogger WARN"
        "log.tag.ConnectivityResources WARN"
        "log.tag.ConnectivityService WARN"
        "log.tag.ContentCaptureManager WARN"
        "log.tag.ContentCaptureService WARN"
        "log.tag.ContentService WARN"
        "log.tag.CpuInfoService WARN"
        "log.tag.CpuStats WARN"
        "log.tag.CrossProfileApps WARN"
        "log.tag.DataConnectionTracker WARN"
        "log.tag.DeviceActivityController WARN"
        "log.tag.DeviceComponent WARN"
        "log.tag.DeviceConfig WARN"
        "log.tag.DeviceConfigManager WARN"
        "log.tag.DeviceConfigProxy WARN"
        "log.tag.DeviceConfigService WARN"
        "log.tag.DeviceCore WARN"
        "log.tag.DeviceEngine WARN"
        "log.tag.DeviceFramework WARN"
        "log.tag.DeviceHandler WARN"
        "log.tag.DeviceIdleController WARN"
        "log.tag.DeviceIdleJobsController WARN"
        "log.tag.DeviceIdleManager WARN"
        "log.tag.DeviceModule WARN"
        "log.tag.DeviceParametersService WARN"
        "log.tag.DevicePolicyControl WARN"
        "log.tag.DevicePolicyControlService WARN"
        "log.tag.DevicePolicyEngine WARN"
        "log.tag.DevicePolicyManager WARN"
        "log.tag.DevicePolicyManagerControl WARN"
        "log.tag.DevicePolicyManagerService WARN"
        "log.tag.DevicePolicyService WARN"
        "log.tag.DevicePolicyServiceControl WARN"
        "log.tag.DevicePolicySystem WARN"
        "log.tag.DeviceProxy WARN"
        "log.tag.DeviceStack WARN"
        "log.tag.DeviceState WARN"
        "log.tag.DeviceStateManager WARN"
        "log.tag.DeviceStateMonitor WARN"
        "log.tag.DeviceStorage WARN"
        "log.tag.DeviceStorageMonitor WARN"
        "log.tag.DeviceSystem WARN"
        "log.tag.DisplayComponent WARN"
        "log.tag.DisplayControl WARN"
        "log.tag.DisplayControlManager WARN"
        "log.tag.DisplayControlService WARN"
        "log.tag.DisplayCore WARN"
        "log.tag.DisplayEngine WARN"
        "log.tag.DisplayFramework WARN"
        "log.tag.DisplayHandler WARN"
        "log.tag.DisplayManager WARN"
        "log.tag.DisplayManagerControl WARN"
        "log.tag.DisplayManagerService WARN"
        "log.tag.DisplayManagerServiceControl WARN"
        "log.tag.DisplayModule WARN"
        "log.tag.DisplayPower WARN"
        "log.tag.DisplayPowerController WARN"
        "log.tag.DisplayPowerState WARN"
        "log.tag.DisplayService WARN"
        "log.tag.DisplayServiceControl WARN"
        "log.tag.DisplayStack WARN"
        "log.tag.DisplaySystem WARN"
        "log.tag.DisplayWindowSettings WARN"
        "log.tag.DiskStatsService WARN"
        "log.tag.DropBoxManager WARN"
        "log.tag.DropBoxService WARN"
        "log.tag.DynamicSystemService WARN"
        "log.tag.EmergencyNumberDb WARN"
        "log.tag.EntropyMixer WARN"
        "log.tag.EntropyRandomization WARN"
        "log.tag.EntropyService WARN"
        "log.tag.EventDataCollector WARN"
        "log.tag.EventLogService WARN"
        "log.tag.ExternalStorageService WARN"
        "log.tag.FaceService WARN"
        "log.tag.FileIntegrityService WARN"
        "log.tag.FileSystemControl WARN"
        "log.tag.FingerprintManager WARN"
        "log.tag.FingerprintService WARN"
        "log.tag.FontManagerService WARN"
        "log.tag.GameManagerService WARN"
        "log.tag.GestureLauncherService WARN"
        "log.tag.GnssBatchingService WARN"
        "log.tag.GnssControl WARN"
        "log.tag.GnssGeofenceProxy WARN"
        "log.tag.GnssLocation WARN"
        "log.tag.GnssLocationProvider WARN"
        "log.tag.GnssManager WARN"
        "log.tag.GnssMeasurementsProvider WARN"
        "log.tag.GnssNavigationMessage WARN"
        "log.tag.GnssNetworkConnectivityHandler WARN"
        "log.tag.GnssProvider WARN"
        "log.tag.GnssService WARN"
        "log.tag.GnssStatusProvider WARN"
        "log.tag.GnssTime WARN"
        "log.tag.GnssTimeUpdateService WARN"
        "log.tag.GnssVisibilityControl WARN"
        "log.tag.GraphicsEnvironment WARN"
        "log.tag.GraphicsStatsService WARN"
        "log.tag.HdmiAudioService WARN"
        "log.tag.HdmiCecService WARN"
        "log.tag.HdmiControlService WARN"
        "log.tag.IccSmsInterfaceManager WARN"
        "log.tag.ImsCall WARN"
        "log.tag.ImsCallForward WARN"
        "log.tag.ImsConfig WARN"
        "log.tag.ImsMediaController WARN"
        "log.tag.ImsMultiEndpoint WARN"
        "log.tag.ImsPhoneCallTracker WARN"
        "log.tag.ImsResolver WARN"
        "log.tag.ImsService WARN"
        "log.tag.ImsUt WARN"
        "log.tag.InputComponent WARN"
        "log.tag.InputControl WARN"
        "log.tag.InputControlManager WARN"
        "log.tag.InputControlService WARN"
        "log.tag.InputCore WARN"
        "log.tag.InputDispatcher WARN"
        "log.tag.InputEngine WARN"
        "log.tag.InputEventReceiver WARN"
        "log.tag.InputFilter WARN"
        "log.tag.InputFramework WARN"
        "log.tag.InputHandler WARN"
        "log.tag.InputManager WARN"
        "log.tag.InputManagerControl WARN"
        "log.tag.InputManagerService WARN"
        "log.tag.InputManagerServiceControl WARN"
        "log.tag.InputMethodClient WARN"
        "log.tag.InputMethodService WARN"
        "log.tag.InputModule WARN"
        "log.tag.InputStack WARN"
        "log.tag.InputStage WARN"
        "log.tag.InputSystem WARN"
        "log.tag.InputTransport WARN"
        "log.tag.IntentFirewall WARN"
        "log.tag.JobComponent WARN"
        "log.tag.JobConcurrencyManager WARN"
        "log.tag.JobController WARN"
        "log.tag.JobControlService WARN"
        "log.tag.JobCore WARN"
        "log.tag.JobEngine WARN"
        "log.tag.JobFramework WARN"
        "log.tag.JobHandler WARN"
        "log.tag.JobHandlerService WARN"
        "log.tag.JobManager WARN"
        "log.tag.JobManagerControl WARN"
        "log.tag.JobManagerService WARN"
        "log.tag.JobModule WARN"
        "log.tag.JobScheduler WARN"
        "log.tag.JobSchedulerService WARN"
        "log.tag.JobService WARN"
        "log.tag.JobServiceControl WARN"
        "log.tag.JobStack WARN"
        "log.tag.JobStore WARN"
        "log.tag.LauncherApps WARN"
        "log.tag.LauncherAppsService WARN"
        "log.tag.LauncherComponent WARN"
        "log.tag.LauncherControl WARN"
        "log.tag.LauncherControlService WARN"
        "log.tag.LauncherCore WARN"
        "log.tag.LauncherEngine WARN"
        "log.tag.LauncherFramework WARN"
        "log.tag.LauncherHandler WARN"
        "log.tag.LauncherManager WARN"
        "log.tag.LauncherManagerService WARN"
        "log.tag.LauncherModel WARN"
        "log.tag.LauncherService WARN"
        "log.tag.LauncherServiceControl WARN"
        "log.tag.LauncherStack WARN"
        "log.tag.LightsManager WARN"
        "log.tag.LightsService WARN"
        "log.tag.LocationComponent WARN"
        "log.tag.LocationControl WARN"
        "log.tag.LocationControlService WARN"
        "log.tag.LocationCore WARN"
        "log.tag.LocationEngine WARN"
        "log.tag.LocationFramework WARN"
        "log.tag.LocationHandler WARN"
        "log.tag.LocationManager WARN"
        "log.tag.LocationManagerControl WARN"
        "log.tag.LocationManagerService WARN"
        "log.tag.LocationManagerServiceControl WARN"
        "log.tag.LocationPolicy WARN"
        "log.tag.LocationPolicyService WARN"
        "log.tag.LocationProvider WARN"
        "log.tag.LocationService WARN"
        "log.tag.LocationServiceControl WARN"
        "log.tag.LocationStack WARN"
        "log.tag.LockGuard WARN"
        "log.tag.LockSettingsService WARN"
        "log.tag.LockSettingsStorage WARN"
        "log.tag.MediaCodec WARN"
        "log.tag.MediaCodecService WARN"
        "log.tag.MediaCommunicationService WARN"
        "log.tag.MediaComponent WARN"
        "log.tag.MediaCore WARN"
        "log.tag.MediaDrmService WARN"
        "log.tag.MediaEngine WARN"
        "log.tag.MediaExtractorService WARN"
        "log.tag.MediaFramework WARN"
        "log.tag.MediaHandler WARN"
        "log.tag.MediaManager WARN"
        "log.tag.MediaMetricsManager WARN"
        "log.tag.MediaModule WARN"
        "log.tag.MediaProjection WARN"
        "log.tag.MediaProjectionControl WARN"
        "log.tag.MediaProjectionControlService WARN"
        "log.tag.MediaProjectionManager WARN"
        "log.tag.MediaProjectionManagerService WARN"
        "log.tag.MediaProjectionService WARN"
        "log.tag.MediaProjectionServiceControl WARN"
        "log.tag.MediaResourceMonitor WARN"
        "log.tag.MediaRouterService WARN"
        "log.tag.MediaSession WARN"
        "log.tag.MediaSessionControl WARN"
        "log.tag.MediaSessionControlManager WARN"
        "log.tag.MediaSessionControlService WARN"
        "log.tag.MediaSessionManager WARN"
        "log.tag.MediaSessionManagerControl WARN"
        "log.tag.MediaSessionManagerService WARN"
        "log.tag.MediaSessionService WARN"
        "log.tag.MediaSessionServiceControl WARN"
        "log.tag.MediaStack WARN"
        "log.tag.MediaTranscodingService WARN"
        "log.tag.MmsNetworkManager WARN"
        "log.tag.MmsRequestManager WARN"
        "log.tag.MmsSendReceive WARN"
        "log.tag.MmsService WARN"
        "log.tag.MmsStorage WARN"
        "log.tag.ModuleMetadataProvider WARN"
        "log.tag.MountControl WARN"
        "log.tag.MountControlService WARN"
        "log.tag.MountManager WARN"
        "log.tag.MountManagerService WARN"
        "log.tag.MountService WARN"
        "log.tag.MountServiceControl WARN"
        "log.tag.MountServiceIdler WARN"
        "log.tag.MtkCallManager WARN"
        "log.tag.MtkCarrierConfig WARN"
        "log.tag.MtkDataConnection WARN"
        "log.tag.MtkDataNetwork WARN"
        "log.tag.MtkDcTracker WARN"
        "log.tag.MtkEccNumber WARN"
        "log.tag.MtkEmergency WARN"
        "log.tag.MtkFeature WARN"
        "log.tag.MtkIms WARN"
        "log.tag.MtkImsCallSession WARN"
        "log.tag.MtkImsConfig WARN"
        "log.tag.MtkImsEmergency WARN"
        "log.tag.MtkImsFeature WARN"
        "log.tag.MtkImsMedia WARN"
        "log.tag.MtkImsRegistration WARN"
        "log.tag.MtkImsUt WARN"
        "log.tag.MtkNetworkAgent WARN"
        "log.tag.MtkNetworkPolicy WARN"
        "log.tag.MtkNetworkStats WARN"
        "log.tag.MtkPhoneFactory WARN"
        "log.tag.MtkRadio WARN"
        "log.tag.MtkRadioInterface WARN"
        "log.tag.MtkRegistration WARN"
        "log.tag.MtkRequest WARN"
        "log.tag.MtkResponse WARN"
        "log.tag.MtkRilClient WARN"
        "log.tag.MtkRilOp WARN"
        "log.tag.MtkRilRequest WARN"
        "log.tag.MtkRilResponse WARN"
        "log.tag.MtkRilSocket WARN"
        "log.tag.MtkServiceStateTracker WARN"
        "log.tag.MtkSignalStrength WARN"
        "log.tag.MtkSocket WARN"
        "log.tag.MtkStats WARN"
        "log.tag.MtkTelephony WARN"
        "log.tag.NetworkAgent WARN"
        "log.tag.NetworkAgentInfo WARN"
        "log.tag.NetworkCollection WARN"
        "log.tag.NetworkComponent WARN"
        "log.tag.NetworkControl WARN"
        "log.tag.NetworkControlManager WARN"
        "log.tag.NetworkControlService WARN"
        "log.tag.NetworkCore WARN"
        "log.tag.NetworkEngine WARN"
        "log.tag.NetworkFramework WARN"
        "log.tag.NetworkHandler WARN"
        "log.tag.NetworkManagement WARN"
        "log.tag.NetworkManager WARN"
        "log.tag.NetworkManagerControl WARN"
        "log.tag.NetworkManagerService WARN"
        "log.tag.NetworkModule WARN"
        "log.tag.NetworkMonitor WARN"
        "log.tag.NetworkPolicy WARN"
        "log.tag.NetworkPolicyCallback WARN"
        "log.tag.NetworkPolicyManager WARN"
        "log.tag.NetworkScoreCache WARN"
        "log.tag.NetworkScoreService WARN"
        "log.tag.NetworkStack WARN"
        "log.tag.NetworkStats WARN"
        "log.tag.NetworkStatsCollection WARN"
        "log.tag.NetworkStatsService WARN"
        "log.tag.NetworkSystem WARN"
        "log.tag.NetworkTimeService WARN"
        "log.tag.NfcComponent WARN"
        "log.tag.NfcControl WARN"
        "log.tag.NfcControlManager WARN"
        "log.tag.NfcControlService WARN"
        "log.tag.NfcCore WARN"
        "log.tag.NfcEngine WARN"
        "log.tag.NfcFramework WARN"
        "log.tag.NfcHandler WARN"
        "log.tag.NfcManager WARN"
        "log.tag.NfcManagerControl WARN"
        "log.tag.NfcManagerService WARN"
        "log.tag.NfcService WARN"
        "log.tag.NfcServiceControl WARN"
        "log.tag.NfcSystem WARN"
        "log.tag.NsdService WARN"
        "log.tag.NotificationComponent WARN"
        "log.tag.NotificationControl WARN"
        "log.tag.NotificationControlManager WARN"
        "log.tag.NotificationControlService WARN"
        "log.tag.NotificationCore WARN"
        "log.tag.NotificationEngine WARN"
        "log.tag.NotificationFramework WARN"
        "log.tag.NotificationHandler WARN"
        "log.tag.NotificationManager WARN"
        "log.tag.NotificationManagerControl WARN"
        "log.tag.NotificationManagerService WARN"
        "log.tag.NotificationService WARN"
        "log.tag.NotificationServiceControl WARN"
        "log.tag.NotificationStack WARN"
        "log.tag.NotificationSystem WARN"
        "log.tag.OemLockService WARN"
        "log.tag.OtaDexoptService WARN"
        "log.tag.PackageComponent WARN"
        "log.tag.PackageControl WARN"
        "log.tag.PackageControlManager WARN"
        "log.tag.PackageControlService WARN"
        "log.tag.PackageCore WARN"
        "log.tag.PackageDexOptimizer WARN"
        "log.tag.PackageEngine WARN"
        "log.tag.PackageFramework WARN"
        "log.tag.PackageHandler WARN"
        "log.tag.PackageInstaller WARN"
        "log.tag.PackageInstallerService WARN"
        "log.tag.PackageInstallerSession WARN"
        "log.tag.PackageManager WARN"
        "log.tag.PackageManagerControl WARN"
        "log.tag.PackageManagerService WARN"
        "log.tag.PackageManagerServiceControl WARN"
        "log.tag.PackageManagerShell WARN"
        "log.tag.PackageModule WARN"
        "log.tag.PackageParser WARN"
        "log.tag.PackageService WARN"
        "log.tag.PackageServiceControl WARN"
        "log.tag.PackageStack WARN"
        "log.tag.PackageState WARN"
        "log.tag.PackageStateModule WARN"
        "log.tag.PackageSystem WARN"
        "log.tag.PackageVerifier WARN"
        "log.tag.PackageVerifierService WARN"
        "log.tag.PackageWatchdog WARN"
        "log.tag.PermissionChecker WARN"
        "log.tag.PermissionManager WARN"
        "log.tag.PermissionManagerService WARN"
        "log.tag.PermissionService WARN"
        "log.tag.PhoneConfigurationManager WARN"
        "log.tag.PhoneInterfaceManager WARN"
        "log.tag.PhoneNumberGeoUtil WARN"
        "log.tag.PhoneNumberUtils WARN"
        "log.tag.PhoneStateListener WARN"
        "log.tag.PhoneSwitcher WARN"
        "log.tag.PowerComponent WARN"
        "log.tag.PowerControl WARN"
        "log.tag.PowerControlManager WARN"
        "log.tag.PowerControlService WARN"
        "log.tag.PowerCore WARN"
        "log.tag.PowerEngine WARN"
        "log.tag.PowerFramework WARN"
        "log.tag.PowerHandler WARN"
        "log.tag.PowerManager WARN"
        "log.tag.PowerManagerControl WARN"
        "log.tag.PowerManagerService WARN"
        "log.tag.PowerManagerServiceControl WARN"
        "log.tag.PowerProfile WARN"
        "log.tag.PowerServiceControl WARN"
        "log.tag.PowerStack WARN"
        "log.tag.PowerStatsService WARN"
        "log.tag.PowerSystem WARN"
        "log.tag.ProcessCpuTracker WARN"
        "log.tag.ProcessInfoService WARN"
        "log.tag.ProcessObserver WARN"
        "log.tag.ProcessRecord WARN"
        "log.tag.ProcessStats WARN"
        "log.tag.ProcessStatsService WARN"
        "log.tag.RestrictedLockUtils WARN"
        "log.tag.RestrictionsManager WARN"
        "log.tag.RestrictionsProvider WARN"
        "log.tag.RoleControllerService WARN"
        "log.tag.RoleManager WARN"
        "log.tag.RoleManagerService WARN"
        "log.tag.RotationLockController WARN"
        "log.tag.RuntimeService WARN"
        "log.tag.SchedulingPolicyService WARN"
        "log.tag.SensorComponent WARN"
        "log.tag.SensorControl WARN"
        "log.tag.SensorControlManager WARN"
        "log.tag.SensorControlService WARN"
        "log.tag.SensorCore WARN"
        "log.tag.SensorEngine WARN"
        "log.tag.SensorFramework WARN"
        "log.tag.SensorHandler WARN"
        "log.tag.SensorManager WARN"
        "log.tag.SensorManagerControl WARN"
        "log.tag.SensorManagerService WARN"
        "log.tag.SensorManagerServiceControl WARN"
        "log.tag.SensorPrivacyService WARN"
        "log.tag.SensorService WARN"
        "log.tag.SensorServiceControl WARN"
        "log.tag.SensorStack WARN"
        "log.tag.SensorSystem WARN"
        "log.tag.ShortcutService WARN"
        "log.tag.SmartspaceService WARN"
        "log.tag.SmsApplication WARN"
        "log.tag.SmsBroadcast WARN"
        "log.tag.SmsBroadcastProxy WARN"
        "log.tag.SmsBroadcastUndelivered WARN"
        "log.tag.SmsController WARN"
        "log.tag.SmsHandler WARN"
        "log.tag.SmsInbound WARN"
        "log.tag.SmsInboundHandler WARN"
        "log.tag.SmsManager WARN"
        "log.tag.SmsMessageBase WARN"
        "log.tag.SmsMessageRecord WARN"
        "log.tag.SmsMessageSender WARN"
        "log.tag.SmsMessageStorage WARN"
        "log.tag.SmsRecord WARN"
        "log.tag.SmsSender WARN"
        "log.tag.SmsService WARN"
        "log.tag.SmsStorageMonitor WARN"
        "log.tag.SmsStorageService WARN"
        "log.tag.SoundTriggerHwService WARN"
        "log.tag.SoundTriggerMiddleware WARN"
        "log.tag.SoundTriggerService WARN"
        "log.tag.StatsCompanionService WARN"
        "log.tag.StatsManager WARN"
        "log.tag.StorageComponent WARN"
        "log.tag.StorageControl WARN"
        "log.tag.StorageControlManager WARN"
        "log.tag.StorageControlService WARN"
        "log.tag.StorageCore WARN"
        "log.tag.StorageEngine WARN"
        "log.tag.StorageFramework WARN"
        "log.tag.StorageHandler WARN"
        "log.tag.StorageManager WARN"
        "log.tag.StorageManagerControl WARN"
        "log.tag.StorageManagerService WARN"
        "log.tag.StorageManagerServiceControl WARN"
        "log.tag.StorageSessionController WARN"
        "log.tag.StorageStack WARN"
        "log.tag.StorageSystem WARN"
        "log.tag.SystemBackupAgent WARN"
        "log.tag.SystemClock WARN"
        "log.tag.SystemComponent WARN"
        "log.tag.SystemConfig WARN"
        "log.tag.SystemConfigService WARN"
        "log.tag.SystemControl WARN"
        "log.tag.SystemControlManager WARN"
        "log.tag.SystemControlService WARN"
        "log.tag.SystemCore WARN"
        "log.tag.SystemEngine WARN"
        "log.tag.SystemFramework WARN"
        "log.tag.SystemHandler WARN"
        "log.tag.SystemManager WARN"
        "log.tag.SystemManagerControl WARN"
        "log.tag.SystemManagerService WARN"
        "log.tag.SystemServer WARN"
        "log.tag.SystemService WARN"
        "log.tag.SystemServiceControl WARN"
        "log.tag.SystemServiceManager WARN"
        "log.tag.SystemStack WARN"
        "log.tag.SystemUI WARN"
        "log.tag.SystemUpdateService WARN"
        "log.tag.TaskSnapshotPersister WARN"
        "log.tag.TelecomService WARN"
        "log.tag.TelephonyComponent WARN"
        "log.tag.TelephonyConnectionService WARN"
        "log.tag.TelephonyControl WARN"
        "log.tag.TelephonyControlManager WARN"
        "log.tag.TelephonyControlService WARN"
        "log.tag.TelephonyCore WARN"
        "log.tag.TelephonyEngine WARN"
        "log.tag.TelephonyFramework WARN"
        "log.tag.TelephonyHandler WARN"
        "log.tag.TelephonyManager WARN"
        "log.tag.TelephonyManagerControl WARN"
        "log.tag.TelephonyManagerService WARN"
        "log.tag.TelephonyManagerServiceControl WARN"
        "log.tag.TelephonyModule WARN"
        "log.tag.TelephonyStack WARN"
        "log.tag.TelephonySystem WARN"
        "log.tag.TetheringInterface WARN"
        "log.tag.TetheringManager WARN"
        "log.tag.TextComponent WARN"
        "log.tag.TextControl WARN"
        "log.tag.TextControlManager WARN"
        "log.tag.TextControlService WARN"
        "log.tag.TextCore WARN"
        "log.tag.TextEngine WARN"
        "log.tag.TextFramework WARN"
        "log.tag.TextHandler WARN"
        "log.tag.TextManager WARN"
        "log.tag.TextManagerService WARN"
        "log.tag.TextModule WARN"
        "log.tag.TextServices WARN"
        "log.tag.TextServicesControl WARN"
        "log.tag.TextServicesManager WARN"
        "log.tag.TextStack WARN"
        "log.tag.TextSystem WARN"
        "log.tag.ThermalComponent WARN"
        "log.tag.ThermalControl WARN"
        "log.tag.ThermalControlManager WARN"
        "log.tag.ThermalControlService WARN"
        "log.tag.ThermalCore WARN"
        "log.tag.ThermalEngine WARN"
        "log.tag.ThermalEventHandler WARN"
        "log.tag.ThermalEventListener WARN"
        "log.tag.ThermalFramework WARN"
        "log.tag.ThermalHandler WARN"
        "log.tag.ThermalListener WARN"
        "log.tag.ThermalManager WARN"
        "log.tag.ThermalManagerControl WARN"
        "log.tag.ThermalManagerService WARN"
        "log.tag.ThermalManagerServiceControl WARN"
        "log.tag.ThermalPolicy WARN"
        "log.tag.ThermalService WARN"
        "log.tag.ThermalServiceControl WARN"
        "log.tag.ThermalStack WARN"
        "log.tag.ThermalStatusListener WARN"
        "log.tag.ThermalSystem WARN"
        "log.tag.TimeZoneRulesManager WARN"
        "log.tag.TombstoneService WARN"
        "log.tag.TvInput WARN"
        "log.tag.TvInputHal WARN"
        "log.tag.TvInputManager WARN"
        "log.tag.TvInputService WARN"
        "log.tag.TvInteractiveAppManager WARN"
        "log.tag.UiModeManager WARN"
        "log.tag.UiModeManagerService WARN"
        "log.tag.UiModeService WARN"
        "log.tag.UiccPhoneBookController WARN"
        "log.tag.UpdateLock WARN"
        "log.tag.UsageEvents WARN"
        "log.tag.UsageStatsService WARN"
        "log.tag.UsbComponent WARN"
        "log.tag.UsbControl WARN"
        "log.tag.UsbControlManager WARN"
        "log.tag.UsbControlService WARN"
        "log.tag.UsbCore WARN"
        "log.tag.UsbEngine WARN"
        "log.tag.UsbFramework WARN"
        "log.tag.UsbHandler WARN"
        "log.tag.UsbManager WARN"
        "log.tag.UsbManagerControl WARN"
        "log.tag.UsbManagerService WARN"
        "log.tag.UsbService WARN"
        "log.tag.UsbServiceControl WARN"
        "log.tag.UsbStack WARN"
        "log.tag.UsbSystem WARN"
        "log.tag.UserHandle WARN"
        "log.tag.UserManager WARN"
        "log.tag.UserManagerService WARN"
        "log.tag.UserService WARN"
        "log.tag.UserSetupComplete WARN"
        "log.tag.VibratorComponent WARN"
        "log.tag.VibratorControl WARN"
        "log.tag.VibratorControlManager WARN"
        "log.tag.VibratorControlService WARN"
        "log.tag.VibratorCore WARN"
        "log.tag.VibratorEngine WARN"
        "log.tag.VibratorFramework WARN"
        "log.tag.VibratorHandler WARN"
        "log.tag.VibratorManager WARN"
        "log.tag.VibratorManagerControl WARN"
        "log.tag.VibratorManagerService WARN"
        "log.tag.VibratorService WARN"
        "log.tag.VibratorServiceControl WARN"
        "log.tag.VibratorStack WARN"
        "log.tag.VibratorSystem WARN"
        "log.tag.Vold WARN"
        "log.tag.VpnProfileStore WARN"
        "log.tag.VpnService WARN"
        "log.tag.WallpaperComponent WARN"
        "log.tag.WallpaperControl WARN"
        "log.tag.WallpaperControlManager WARN"
        "log.tag.WallpaperControlService WARN"
        "log.tag.WallpaperCore WARN"
        "log.tag.WallpaperEngine WARN"
        "log.tag.WallpaperFramework WARN"
        "log.tag.WallpaperHandler WARN"
        "log.tag.WallpaperManager WARN"
        "log.tag.WallpaperManagerControl WARN"
        "log.tag.WallpaperManagerService WARN"
        "log.tag.WallpaperService WARN"
        "log.tag.WallpaperServiceControl WARN"
        "log.tag.WallpaperStack WARN"
        "log.tag.WallpaperSystem WARN"
        "log.tag.WifiActiveModeManager WARN"
        "log.tag.WifiAware WARN"
        "log.tag.WifiAwareManager WARN"
        "log.tag.WifiAwareService WARN"
        "log.tag.WifiAwareStateManager WARN"
        "log.tag.WifiBackupRestore WARN"
        "log.tag.WifiClientModeManager WARN"
        "log.tag.WifiComponent WARN"
        "log.tag.WifiConfig WARN"
        "log.tag.WifiConfigManager WARN"
        "log.tag.WifiConfigStore WARN"
        "log.tag.WifiControl WARN"
        "log.tag.WifiControlManager WARN"
        "log.tag.WifiControlService WARN"
        "log.tag.WifiController WARN"
        "log.tag.WifiCore WARN"
        "log.tag.WifiCountryCode WARN"
        "log.tag.WifiEngine WARN"
        "log.tag.WifiFramework WARN"
        "log.tag.WifiHandler WARN"
        "log.tag.WifiManager WARN"
        "log.tag.WifiManagerControl WARN"
        "log.tag.WifiManagerService WARN"
        "log.tag.WifiManagerServiceControl WARN"
        "log.tag.WifiModule WARN"
        "log.tag.WifiMonitor WARN"
        "log.tag.WifiNetwork WARN"
        "log.tag.WifiNetworkAgent WARN"
        "log.tag.WifiNetworkFactory WARN"
        "log.tag.WifiP2p WARN"
        "log.tag.WifiP2pConfig WARN"
        "log.tag.WifiP2pConnection WARN"
        "log.tag.WifiP2pDevice WARN"
        "log.tag.WifiP2pDeviceList WARN"
        "log.tag.WifiP2pDiscovery WARN"
        "log.tag.WifiP2pGroup WARN"
        "log.tag.WifiP2pImpl WARN"
        "log.tag.WifiP2pLink WARN"
        "log.tag.WifiP2pManager WARN"
        "log.tag.WifiP2pMonitor WARN"
        "log.tag.WifiP2pMonitorImpl WARN"
        "log.tag.WifiP2pMonitorService WARN"
        "log.tag.WifiP2pNative WARN"
        "log.tag.WifiP2pScan WARN"
        "log.tag.WifiP2pService WARN"
        "log.tag.WifiP2pServiceImpl WARN"
        "log.tag.WifiP2pSettings WARN"
        "log.tag.WifiP2pState WARN"
        "log.tag.WifiScanningService WARN"
        "log.tag.WifiService WARN"
        "log.tag.WifiServiceControl WARN"
        "log.tag.WifiStack WARN"
        "log.tag.WifiStateMachine WARN"
        "log.tag.WifiSystem WARN"
        "log.tag.WifiThreadRunner WARN"
        "log.tag.WifiVendorHal WARN"
        "log.tag.WindowAnimator WARN"
        "log.tag.WindowComponent WARN"
        "log.tag.WindowControl WARN"
        "log.tag.WindowControlManager WARN"
        "log.tag.WindowControlService WARN"
        "log.tag.WindowCore WARN"
        "log.tag.WindowEngine WARN"
        "log.tag.WindowFramework WARN"
        "log.tag.WindowHandler WARN"
        "log.tag.WindowManager WARN"
        "log.tag.WindowManagerControl WARN"
        "log.tag.WindowManagerService WARN"
        "log.tag.WindowManagerServiceControl WARN"
        "log.tag.WindowManagerShell WARN"
        "log.tag.WindowServiceControl WARN"
        "log.tag.WindowStack WARN"
        "log.tag.WindowState WARN"
        "log.tag.WindowSurfaceController WARN"
        "log.tag.WirelessCharger WARN"
        "log.tag.Zygote WARN"
    )

    for cmd in "${log_tags[@]}"; do
        IFS=' ' read -r name value <<< "$cmd"
        setprop "$name" "$value" 2>>"$log_file"
    done
    echo "[+] Log Suppression Applied (540 tags)"
}

apply_optimizations() {
    print_progress "Applying Ultra Touch Sensitivity"
    touch_settings=(
        "touch.size.calibration none"
        "touch.pressure.calibration none"
        "touch.distance.calibration none"
        "touch.gestureMode pointer"
        "touch.orientationAware 1"
        "touch.deviceType touchScreen"
        "touch.tap.interval 30"
        "touch.doubletap.interval 100"
        "touch.scroll.sensitivity 2.0"
        "touch.fling.velocity 1.5"
        "touch.recoil.compensation 0.8"
    )

    print_progress "Applying Graphics Boost"
    graphics_settings=(
        "debug.sf.hw 1"
        "debug.egl.hw 1"
        "debug.sf.enable_gl_backpressure 0"
        "debug.sf.latch_unsignaled 1"
        "debug.sf.enable_hwc_vds 1"
        "debug.sf.predict_hwc_composition_strategy true"
        "debug.hwui.use_hint_manager true"
        "debug.hwui.use_buffer_age 1"
        "debug.renderengine.backend skiagputhreaded"
        "debug.sf.use_phase_offsets_as_durations true"
        "debug.sf.early_phase_offset_ns -6666666"
        "debug.sf.early_app_phase_offset_ns -6666666"
        "debug.sf.early_gl_phase_offset_ns -6666666"
        "debug.sf.high_fps_early_phase_offset_ns -6666666"
        "debug.sf.frame_rate_multiple 3"
        "debug.hwui.overdraw none"
        "debug.hwui.target_cpu_time_percent 95"
        "debug.hwui.recoil_reduction 0.7"
    )

    print_progress "Applying VSync Optimization (Smooth Drag)"
    vsync_settings=(
        "debug.egl.swapinterval 0"
        "debug.gr.swapinterval 0"
        "debug.sf.swapinterval 0"
        "debug.sf.frame_timing_optimization 1"
    )

    print_progress "Applying Max Performance Boost"
    system_settings=(
        "low_power 0"
        "cached_apps_freezer enabled"
        "DYNAMIC_PERFORMANCE_STATUS 1"
        "game_auto_temperature 0"
        "game_dashboard_always_on 1"
        "power.performance_mode ultra"
        "persist.sys.max_cpu_freq 0"
    )

    print_progress "Applying Free Fire Headshot Optimizer"
    game_overlay=(
        "game_overlay com.dts.freefireth mode=3,angle=true,fps=$refresh_rate,loadingBoost=999999999"
        "game_overlay com.dts.freefiremax mode=3,angle=true,fps=$refresh_rate,loadingBoost=999999999,priority=1"
    )

    print_progress "Disabling Heavy Graphics Effects"
    disable_effects=(
        "debug.egl.force_msaa 0"
        "debug.hwui.force_fxaa 0"
        "debug.hwui.force_smaa 0"
        "debug.hwui.force_msaa 0"
        "debug.hwui.force_txaa 0"
        "debug.hwui.force_csaa 0"
        "debug.hwui.force_dlss 0"
    )

    print_progress "Stopping Background Services"
    background_services=(
        "com.samsung.android.game.gos"
        "com.xiaomi.joyose"
        "com.google.android.gms"
        "com.android.vending"
        "com.google.android.gsf"
    )

    for cmd in "${touch_settings[@]}"; do
        IFS=' ' read -r key value <<< "$cmd"
        settings put system "$key" "$value" 2>>"$log_file"
    done
    echo "[+] Ultra Touch Sensitivity Applied"

    for cmd in "${graphics_settings[@]}"; do
        IFS=' ' read -r key value <<< "$cmd"
        setprop "$key" "$value" 2>>"$log_file"
    done
    echo "[+] Graphics Boost Applied"

    for cmd in "${vsync_settings[@]}"; do
        IFS=' ' read -r key value <<< "$cmd"
        setprop "$key" "$value" 2>>"$log_file"
    done
    echo "[+] VSync Optimization Applied"

    for cmd in "${system_settings[@]}"; do
        IFS=' ' read -r key value <<< "$cmd"
        settings put global "$key" "$value" 2>>"$log_file"
    done
    echo "[+] Max Performance Boost Applied"

    for cmd in "${game_overlay[@]}"; do
        IFS=' ' read -r namespace key value <<< "$cmd"
        device_config put "$namespace" "$key" "$value" 2>>"$log_file"
    done
    echo "[+] Free Fire Headshot Optimizer Applied"

    for cmd in "${disable_effects[@]}"; do
        IFS=' ' read -r key value <<< "$cmd"
        setprop "$key" "$value" 2>>"$log_file"
    done
    echo "[+] Heavy Graphics Effects Disabled"

    for service in "${background_services[@]}"; do
        stop "$service" 2>>"$log_file" || true
    done
    echo "[+] Background Services Stopped"

    print_progress "Applying Ultra Frame Timing"
    frame_ns=$(echo "1000000000 / $refresh_rate" | bc)
    early_app=$(echo "$frame_ns * 0.2" | bc)
    early_sf=$(echo "$frame_ns * 0.15" | bc)
    setprop debug.sf.early.app.duration "$early_app" 2>>"$log_file"
    setprop debug.sf.early.sf.duration "$early_sf" 2>>"$log_file"
    setprop debug.sf.early_app_phase_offset_ns "-$early_app" 2>>"$log_file"
    setprop debug.sf.early_phase_offset_ns "-$early_sf" 2>>"$log_file"
    echo "[+] Ultra Frame Timing Applied"

    print_progress "Clearing Logcat Buffer"
    logcat -G 64K 2>>"$log_file"
    logcat -c 2>>"$log_file"
    echo "[+] Logcat Buffer Cleared"
}

check_compatibility
log
apply_optimizations

echo "╔══════════════════════════════════════════════════════════════╗"
echo "║          Sensi PlusX V3 Completed                            ║"
echo "╠══════════════════════════════════════════════════════════════╩╗"
echo "║ [*] Script executed successfully on $now                     ║"
echo "║ [*] Thank you for using Sensi PlusX V3!                    ║"
echo "║ [*] Author: Kysertweaks | Country: VietNam 🇻🇳            ║"
echo "╚══════════════════════════════════════════════════════════════╝"
