#!/system/bin/sh

log_file="/data/local/tmp/sensi_plusx_v2_log.txt"
now=$(date '+%Y-%m-%d %H:%M:%S')

print_progress() {
    local msg=$1
    echo "[*] $msg..."
    for i in {1..5}; do
        echo -n "█"
        sleep 0.1
    done
    echo " Done!"
}

print_banner() {
    clear
    echo "╔══════════════════════════════════════════════════════════════╗"
    echo "║          Sensi PlusX V2 by Kysertweaks                       ║"
    echo "╠═══════════════════════════════════════════════════════╦════╩╗"
    echo "║  ███████╗███████╗███╗   ██╗███████╗██╗    ██╗██╗██╗   ██╗ ║"
    echo "║  ██╔════╝██╔════╝████╗  ██║██╔════╝██║    ██║██║██║   ██║ ║"
    echo "║  ███████╗█████╗  ██╔██╗ ██║█████╗  ██║ █╗ ██║██║██║   ██║ ║"
    echo "║  ╚════██║██╔══╝  ██║╚██╗██║██╔══╝  ██║███╗██║██║██║   ██║ ║"
    echo "║  ███████║███████╗██║ ╚████║██║     ╚███╔███╔╝██║╚██████╔╝ ║"
    echo "║  ╚══════╝╚══════╝╚═╝  ╚═══╝╚═╝      ╚══╝╚══╝ ╚═╝ ╚═════╝  ║"
    echo "╠═════════════════════╦═════════════════════════════════╩═════╩╗"
    echo "║ Power Features:     ║ Touch Sensitivity                     ║"
    echo "║ - Ultra Responsive  ║ Graphics Boost                        ║"
    echo "║ - Smooth Aim        ║ Game Overlay (Free Fire)              ║"
    echo "║ - Max Performance   ║ Log Suppression (700 tags)            ║"
    echo "╠═════════════════════╩═════════════════════════════════════════╩╗"
    echo "║ © Copyright 2025 by Kysertweaks                               ║"
    echo "║ Date: $(date)                                               ║"
    echo "║ Country: VietNam 🇻🇳                                         ║"
    echo "║ PID: $$ | UID: $(id -u)                                     ║"
    echo "╚══════════════════════════════════════════════════════════════╝"
}

if [ -f "$log_file" ]; then
    last_run=$(cat "$log_file")
    echo "[*] Last Run: $last_run"
else
    echo "[*] Welcome to Sensi PlusX V2!"
fi

echo "$now" > "$log_file"

print_banner

refresh_rate=$(dumpsys SurfaceFlinger | grep "refresh-rate" | awk '{printf("%d ", $3)}' | head -n 1)
[ -z "$refresh_rate" ] && refresh_rate=60
brand=$(getprop ro.product.system.brand)
storage=$(df /data | awk 'NR==2 { total=($2+$3)/1024/1024; used=$3/1024/1024; printf "%.2f / %.0f GB", used, total }')
vulkan_support=$(getprop ro.hardware.vulkan)

echo "[+] Script Name: Sensi PlusX V2"
echo "[+] Refresh Rate: ${refresh_rate}Hz"
echo "[+] Brand: $brand"
echo "[+] Storage: $storage"
echo "[+] Vulkan Support: ${vulkan_support:-Not Available}"
echo "---------------------------------------------------------------"

check_compatibility() {
    print_progress "Checking Device Compatibility"
    if [ "$refresh_rate" -lt 60 ]; then
        echo "[!] Warning: Low refresh rate detected (${refresh_rate}Hz). Performance may be limited." >> "$log_file"
    fi
    if [ -z "$vulkan_support" ]; then
        echo "[*] Vulkan not supported, falling back to OpenGL"
        setprop debug.renderengine.backend skiagl 2>>"$log_file"
    fi
}

log() {
    print_progress "Applying Log Suppression"
    log_tags=(
        "log.tag.stats_log WARN"
        "log.tag.FA WARN"
        "log.tag.AF::MmapTrack WARN"
        "log.tag.AF::OutputTrack WARN"
        "log.tag.AF::PatchRecord WARN"
        "log.tag.AF::PatchTrack WARN"
        "log.tag.AF::RecordHandle WARN"
        "log.tag.AF::RecordTrack WARN"
        "log.tag.AF::Track WARN"
        "log.tag.AF::TrackBase WARN"
        "log.tag.AF::TrackHandle WARN"
        "log.tag.APM-KpiMonitor WARN"
        "log.tag.APM-ServiceJ WARN"
        "log.tag.APM-SessionJ WARN"
        "log.tag.APM-SessionN WARN"
        "log.tag.APM-Subscriber WARN"
        "log.tag.APM::AudioCollections WARN"
        "log.tag.APM::AudioInputDescriptor WARN"
        "log.tag.APM::AudioOutputDescriptor WARN"
        "log.tag.APM::AudioPatch WARN"
        "log.tag.APM::AudioPolicyEngine WARN"
        "log.tag.APM::AudioPolicyEngine::Base WARN"
        "log.tag.APM::AudioPolicyEngine::Config WARN"
        "log.tag.APM::AudioPolicyEngine::ProductStrategy WARN"
        "log.tag.APM::AudioPolicyEngine::VolumeGroup WARN"
        "log.tag.APM::Devices WARN"
        "log.tag.APM::IOProfile WARN"
        "log.tag.APM::Serializer WARN"
        "log.tag.APM::VolumeCurve WARN"
        "log.tag.APM_AudioPolicyManager WARN"
        "log.tag.APM_ClientDescriptor WARN"
        "log.tag.AT WARN"
        "log.tag.AccountManager WARN"
        "log.tag.ActivityManager WARN"
        "log.tag.ActivityManagerService WARN"
        "log.tag.ActivityTaskManager WARN"
        "log.tag.ActivityTaskManagerService WARN"
        "log.tag.AdnRecord WARN"
        "log.tag.AdnRecordCache WARN"
        "log.tag.AdnRecordLoader WARN"
        "log.tag.AirplaneHandler WARN"
        "log.tag.AlarmManager WARN"
        "log.tag.AlarmManagerService WARN"
        "log.tag.AndroidRuntime WARN"
        "log.tag.AppOps WARN"
        "log.tag.AudioAttributes WARN"
        "log.tag.AudioEffect WARN"
        "log.tag.AudioFlinger WARN"
        "log.tag.AudioFlinger::DeviceEffectProxy WARN"
        "log.tag.AudioFlinger::EffectBase WARN"
        "log.tag.AudioFlinger::EffectChain WARN"
        "log.tag.AudioFlinger::EffectHandle WARN"
        "log.tag.AudioFlinger::EffectModule WARN"
        "log.tag.AudioFlinger_Threads WARN"
        "log.tag.AudioHwDevice WARN"
        "log.tag.AudioManager WARN"
        "log.tag.AudioPolicy WARN"
        "log.tag.AudioPolicyEffects WARN"
        "log.tag.AudioPolicyInterfaceImpl WARN"
        "log.tag.AudioPolicyManager WARN"
        "log.tag.AudioPolicyService WARN"
        "log.tag.AudioProductStrategy WARN"
        "log.tag.AudioRecord WARN"
        "log.tag.AudioService WARN"
        "log.tag.AudioSystem WARN"
        "log.tag.AudioTrack WARN"
        "log.tag.AudioTrackShared WARN"
        "log.tag.AudioVolumeGroup WARN"
        "log.tag.BackupManager WARN"
        "log.tag.BatteryManager WARN"
        "log.tag.BatteryStatsService WARN"
        "log.tag.BluetoothAdapter WARN"
        "log.tag.BluetoothDevice WARN"
        "log.tag.BluetoothGattService WARN"
        "log.tag.BluetoothHidService WARN"
        "log.tag.BluetoothManager WARN"
        "log.tag.BluetoothMapService WARN"
        "log.tag.BluetoothPanService WARN"
        "log.tag.BluetoothPbapService WARN"
        "log.tag.BluetoothSapService WARN"
        "log.tag.BluetoothService WARN"
        "log.tag.BluetoothSocket WARN"
        "log.tag.BufferQueueDump WARN"
        "log.tag.BufferQueueProducer WARN"
        "log.tag.C2K_AT WARN"
        "log.tag.C2K_ATConfig WARN"
        "log.tag.C2K_RILC WARN"
        "log.tag.CAM2PORT_ WARN"
        "log.tag.CapaSwitch WARN"
        "log.tag.CarrierExpressServiceImpl WARN"
        "log.tag.CarrierExpressServiceImplExt WARN"
        "log.tag.ClipboardManager WARN"
        "log.tag.ConnectivityManager WARN"
        "log.tag.ConnectivityService WARN"
        "log.tag.ConsumerIrService WARN"
        "log.tag.ContentManager WARN"
        "log.tag.CountryDetector WARN"
        "log.tag.DMC-ApmService WARN"
        "log.tag.DMC-Core WARN"
        "log.tag.DMC-DmcService WARN"
        "log.tag.DMC-EventsSubscriber WARN"
        "log.tag.DMC-ReqQManager WARN"
        "log.tag.DMC-SessionManager WARN"
        "log.tag.DMC-TranslatorLoader WARN"
        "log.tag.DMC-TranslatorUtils WARN"
        "log.tag.DSSelector WARN"
        "log.tag.DSSelectorOP01 WARN"
        "log.tag.DSSelectorOP02 WARN"
        "log.tag.DSSelectorOP09 WARN"
        "log.tag.DSSelectorOP18 WARN"
        "log.tag.DSSelectorOm WARN"
        "log.tag.DSSelectorUtil WARN"
        "log.tag.DataDispatcher WARN"
        "log.tag.DeviceIdleController WARN"
        "log.tag.DevicePolicyManager WARN"
        "log.tag.DevicePolicyManagerService WARN"
        "log.tag.DisplayManager WARN"
        "log.tag.DisplayManagerService WARN"
        "log.tag.DockObserver WARN"
        "log.tag.DownloadManager WARN"
        "log.tag.ExternalSimMgr WARN"
        "log.tag.FastCapture WARN"
        "log.tag.FastMixer WARN"
        "log.tag.FastMixerState WARN"
        "log.tag.FastThread WARN"
        "log.tag.FragmentManager WARN"
        "log.tag.FuseDaemon WARN"
        "log.tag.GAv4 WARN"
        "log.tag.GraphicsStats WARN"
        "log.tag.GsmCallTkrHlpr WARN"
        "log.tag.GsmCdmaConn WARN"
        "log.tag.GsmCdmaPhone WARN"
        "log.tag.HardwarePropertiesManager WARN"
        "log.tag.HardwareService WARN"
        "log.tag.IAudioFlinger WARN"
        "log.tag.IMSRILRequest WARN"
        "log.tag.IMS_RILA WARN"
        "log.tag.IccCardProxy WARN"
        "log.tag.IccPhoneBookIM WARN"
        "log.tag.IccProvider WARN"
        "log.tag.ImsApp WARN"
        "log.tag.ImsBaseCommands WARN"
        "log.tag.ImsCall WARN"
        "log.tag.ImsCallProfile WARN"
        "log.tag.ImsCallSession WARN"
        "log.tag.ImsEcbm WARN"
        "log.tag.ImsEcbmProxy WARN"
        "log.tag.ImsManager WARN"
        "log.tag.ImsPhone WARN"
        "log.tag.ImsPhoneBase WARN"
        "log.tag.ImsPhoneCall WARN"
        "log.tag.ImsService WARN"
        "log.tag.ImsVTProvider WARN"
        "log.tag.InputDispatcher WARN"
        "log.tag.InputManager WARN"
        "log.tag.InputMethodManager WARN"
        "log.tag.InputMethodManagerService WARN"
        "log.tag.InterfaceManager WARN"
        "log.tag.IsimFileHandler WARN"
        "log.tag.IsimRecords WARN"
        "log.tag.JobScheduler WARN"
        "log.tag.KeyguardManager WARN"
        "log.tag.LCM-Subscriber WARN"
        "log.tag.LIBC2K_RIL WARN"
        "log.tag.LocationManager WARN"
        "log.tag.LocationManagerService WARN"
        "log.tag.LocationProvider WARN"
        "log.tag.MAPI-CommandProcessor WARN"
        "log.tag.MAPI-MdiRedirector WARN"
        "log.tag.MAPI-MdiRedirectorCtrl WARN"
        "log.tag.MAPI-NetworkSocketConnection WARN"
        "log.tag.MAPI-SocketConnection WARN"
        "log.tag.MAPI-SocketListener WARN"
        "log.tag.MAPI-TranslatorManager WARN"
        "log.tag.MDM-Subscriber WARN"
        "log.tag.MTKSST WARN"
        "log.tag.MTK_APPList WARN"
        "log.tag.MediaPlayer WARN"
        "log.tag.MediaPlayerService WARN"
        "log.tag.MediaRouter WARN"
        "log.tag.MediaSession WARN"
        "log.tag.MipcEventHandler WARN"
        "log.tag.MountService WARN"
        "log.tag.MtkAdnRecord WARN"
        "log.tag.MtkCsimFH WARN"
        "log.tag.MtkEmbmsAdaptor WARN"
        "log.tag.MtkFactory WARN"
        "log.tag.MtkGsmCdmaConn WARN"
        "log.tag.MtkIccCardProxy WARN"
        "log.tag.MtkIccPHBIM WARN"
        "log.tag.MtkIccProvider WARN"
        "log.tag.MtkImsManager WARN"
        "log.tag.MtkImsService WARN"
        "log.tag.MtkIsimFH WARN"
        "log.tag.MtkPhoneNotifr WARN"
        "log.tag.MtkPhoneNumberUtils WARN"
        "log.tag.MtkPhoneSwitcher WARN"
        "log.tag.MtkRecordLoader WARN"
        "log.tag.MtkRuimFH WARN"
        "log.tag.MtkSIMFH WARN"
        "log.tag.MtkSIMRecords WARN"
        "log.tag.MtkSmsCbHeader WARN"
        "log.tag.MtkSmsManager WARN"
        "log.tag.MtkSmsMessage WARN"
        "log.tag.MtkSpnOverride WARN"
        "log.tag.MtkSubCtrl WARN"
        "log.tag.MtkTelephonyManagerEx WARN"
        "log.tag.MtkUiccCard WARN"
        "log.tag.MtkUiccCardApp WARN"
        "log.tag.MtkUiccCtrl WARN"
        "log.tag.MtkUsimFH WARN"
        "log.tag.MtkUsimPhoneBookManager WARN"
        "log.tag.MwiRIL WARN"
        "log.tag.NetAgentService WARN"
        "log.tag.NetAgent_IO WARN"
        "log.tag.NetLnkEventHdlr WARN"
        "log.tag.NetworkManagement WARN"
        "log.tag.NetworkManagementService WARN"
        "log.tag.NetworkPolicy WARN"
        "log.tag.NetworkPolicyManagerService WARN"
        "log.tag.NetworkStats WARN"
        "log.tag.NetworkTimeUpdateService WARN"
        "log.tag.NotificationManager WARN"
        "log.tag.NotificationManagerService WARN"
        "log.tag.OperatorUtils WARN"
        "log.tag.PKM-Lib WARN"
        "log.tag.PKM-MDM WARN"
        "log.tag.PKM-Monitor WARN"
        "log.tag.PKM-SA WARN"
        "log.tag.PKM-Service WARN"
        "log.tag.PQ_DS WARN"
        "log.tag.PackageInstaller WARN"
        "log.tag.PackageManager WARN"
        "log.tag.PersistentDataBlockManager WARN"
        "log.tag.Phone WARN"
        "log.tag.PhoneConfigurationSettings WARN"
        "log.tag.PhoneFactory WARN"
        "log.tag.PowerHalAddressUitls WARN"
        "log.tag.PowerHalMgrImpl WARN"
        "log.tag.PowerHalMgrServiceImpl WARN"
        "log.tag.PowerHalWifiMonitor WARN"
        "log.tag.PowerManager WARN"
        "log.tag.PowerManagerService WARN"
        "log.tag.PrintManager WARN"
        "log.tag.ProcessStats WARN"
        "log.tag.ProxyController WARN"
        "log.tag.RFX WARN"
        "log.tag.RIL WARN"
        "log.tag.RIL-Fusion WARN"
        "log.tag.RIL-Netlink WARN"
        "log.tag.RIL-Parcel WARN"
        "log.tag.RIL-SocListen WARN"
        "log.tag.RIL-Socket WARN"
        "log.tag.RILC WARN"
        "log.tag.RILC-OP WARN"
        "log.tag.RILD WARN"
        "log.tag.RILMD2-SS WARN"
        "log.tag.RIL_UIM_SOCKET WARN"
        "log.tag.RadioManager WARN"
        "log.tag.RfxAction WARN"
        "log.tag.RfxBaseHandler WARN"
        "log.tag.RfxChannelMgr WARN"
        "log.tag.RfxCloneMgr WARN"
        "log.tag.RfxContFactory WARN"
        "log.tag.RfxController WARN"
        "log.tag.RfxDebugInfo WARN"
        "log.tag.RfxDisThread WARN"
        "log.tag.RfxFragEnc WARN"
        "log.tag.RfxHandlerMgr WARN"
        "log.tag.RfxIdToMsgId WARN"
        "log.tag.RfxIdToStr WARN"
        "log.tag.RfxMainThread WARN"
        "log.tag.RfxMclDisThread WARN"
        "log.tag.RfxMclMessenger WARN"
        "log.tag.RfxMclStatusMgr WARN"
        "log.tag.RfxMessage WARN"
        "log.tag.RfxObject WARN"
        "log.tag.RfxOpUtils WARN"
        "log.tag.RfxRilAdapter WARN"
        "log.tag.RfxRilUtils WARN"
        "log.tag.RfxRoot WARN"
        "log.tag.RfxStatusMgr WARN"
        "log.tag.RfxTimer WARN"
        "log.tag.RilClient WARN"
        "log.tag.RilOpProxy WARN"
        "log.tag.RmmCapa WARN"
        "log.tag.RmmCommSimOpReq WARN"
        "log.tag.RmmDcEvent WARN"
        "log.tag.RmmDcPdnManager WARN"
        "log.tag.RmmDcUrcHandler WARN"
        "log.tag.RmmDcUtility WARN"
        "log.tag.RmmEccNumberReqHdlr WARN"
        "log.tag.RmmEccNumberUrcHandler WARN"
        "log.tag.RmmEmbmsReq WARN"
        "log.tag.RmmEmbmsUrc WARN"
        "log.tag.RmmImsCtlReqHdl WARN"
        "log.tag.RmmImsCtlUrcHdl WARN"
        "log.tag.RmmMwi WARN"
        "log.tag.RmmNwAsyncHdlr WARN"
        "log.tag.RmmNwHdlr WARN"
        "log.tag.RmmNwNrtReqHdlr WARN"
        "log.tag.RmmNwRTReqHdlr WARN"
        "log.tag.RmmNwRatSwHdlr WARN"
        "log.tag.RmmNwReqHdlr WARN"
        "log.tag.RmmNwUrcHdlr WARN"
        "log.tag.RmmOemHandler WARN"
        "log.tag.RmmOpRadioReq WARN"
        "log.tag.RmmPhbReq WARN"
        "log.tag.RmmPhbUrc WARN"
        "log.tag.RmmRadioReq WARN"
        "log.tag.RmmSimBaseHandler WARN"
        "log.tag.RmmSimCommReq WARN"
        "log.tag.RmmSimCommUrc WARN"
        "log.tag.RmmWp WARN"
        "log.tag.RtmCapa WARN"
        "log.tag.RtmCommSimCtrl WARN"
        "log.tag.RtmDC WARN"
        "log.tag.RtmEccNumberController WARN"
        "log.tag.RtmEmbmsAt WARN"
        "log.tag.RtmEmbmsUtil WARN"
        "log.tag.RtmIms WARN"
        "log.tag.RtmImsConference WARN"
        "log.tag.RtmImsConfigController WARN"
        "log.tag.RtmImsDialog WARN"
        "log.tag.RtmModeCont WARN"
        "log.tag.RtmMwi WARN"
        "log.tag.RtmNwCtrl WARN"
        "log.tag.RtmPhb WARN"
        "log.tag.RtmRadioConfig WARN"
        "log.tag.RtmRadioCont WARN"
        "log.tag.RtmWp WARN"
        "log.tag.SIMRecords WARN"
        "log.tag.SQLiteQueryBuilder WARN"
        "log.tag.SensorManager WARN"
        "log.tag.ServiceManager WARN"
        "log.tag.SimSwitchOP01 WARN"
        "log.tag.SimSwitchOP02 WARN"
        "log.tag.SimSwitchOP18 WARN"
        "log.tag.SlotQueueEntry WARN"
        "log.tag.SpnOverride WARN"
        "log.tag.StatusBarManagerService WARN"
        "log.tag.StorageManager WARN"
        "log.tag.SurfaceFlinger WARN"
        "log.tag.SystemServer WARN"
        "log.tag.Telecom WARN"
        "log.tag.TelephonyManager WARN"
        "log.tag.TelephonyRegistry WARN"
        "log.tag.ThermalManager WARN"
        "log.tag.ToneGenerator WARN"
        "log.tag.UiccCard WARN"
        "log.tag.UiccController WARN"
        "log.tag.UsbHostManager WARN"
        "log.tag.UsbManager WARN"
        "log.tag.UxUtility WARN"
        "log.tag.VT WARN"
        "log.tag.VibratorService WARN"
        "log.tag.VpnManager WARN"
        "log.tag.VsimAdaptor WARN"
        "log.tag.WORLDMODE WARN"
        "log.tag.WallpaperManager WARN"
        "log.tag.WfoApp WARN"
        "log.tag.WifiManager WARN"
        "log.tag.WindowManager WARN"
        "log.tag.WindowManagerService WARN"
        "log.tag.WpfaCcciDataHeaderEncoder WARN"
        "log.tag.WpfaCcciReader WARN"
        "log.tag.WpfaCcciSender WARN"
        "log.tag.WpfaControlMsgHandler WARN"
        "log.tag.WpfaDriver WARN"
        "log.tag.WpfaDriverAccept WARN"
        "log.tag.WpfaDriverAdapter WARN"
        "log.tag.WpfaDriverDeReg WARN"
        "log.tag.WpfaDriverMessage WARN"
        "log.tag.WpfaDriverRegFilter WARN"
        "log.tag.WpfaDriverULIpPkt WARN"
        "log.tag.WpfaDriverUtilis WARN"
        "log.tag.WpfaDriverVersion WARN"
        "log.tag.WpfaFilterRuleReqHandler WARN"
        "log.tag.WpfaParsing WARN"
        "log.tag.WpfaRingBuffer WARN"
        "log.tag.WpfaRuleContainer WARN"
        "log.tag.WpfaRuleRegister WARN"
        "log.tag.WpfaShmAccessController WARN"
        "log.tag.WpfaShmReadMsgHandler WARN"
        "log.tag.WpfaShmSynchronizer WARN"
        "log.tag.WpfaShmWriteMsgHandler WARN"
        "log.tag.brevent.event WARN"
        "log.tag.libPowerHal WARN"
        "log.tag.libfuse WARN"
        "log.tag.mipc_lib WARN"
        "log.tag.mtkpower@impl WARN"
        "log.tag.mtkpower_client WARN"
        "log.tag.trm_lib WARN"
        "log.tag.wpfa_iptable_android WARN"
        "log.tag.Networklogger WARN"
        "log.tag.AppWidgetService WARN"
        "log.tag.AppWidgetServiceImpl WARN"
        "log.tag.AudioPort WARN"
        "log.tag.AutoStartManager WARN"
        "log.tag.BatteryExternalStatsWorker WARN"
        "log.tag.BatteryStatsImpl WARN"
        "log.tag.Binder WARN"
        "log.tag.BluetoothA2dp WARN"
        "log.tag.BluetoothHeadset WARN"
        "log.tag.BluetoothMap WARN"
        "log.tag.BluetoothPbap WARN"
        "log.tag.BluetoothProfile WARN"
        "log.tag.BroadcastQueue WARN"
        "log.tag.BroadcastRadio WARN"
        "log.tag.CameraService WARN"
        "log.tag.CarrierConfig WARN"
        "log.tag.CdmaServiceStateTracker WARN"
        "log.tag.CellBroadcastService WARN"
        "log.tag.CompatibilityChangeReporter WARN"
        "log.tag.ContentService WARN"
        "log.tag.DeviceStorageMonitor WARN"
        "log.tag.DropBoxManager WARN"
        "log.tag.EmergencyNumberDb WARN"
        "log.tag.EntropyMixer WARN"
        "log.tag.EventLogService WARN"
        "log.tag.FingerprintService WARN"
        "log.tag.GnssLocationProvider WARN"
        "log.tag.GnssManager WARN"
        "log.tag.GraphicsEnvironment WARN"
        "log.tag.HdmiControlService WARN"
        "log.tag.IccSmsInterfaceManager WARN"
        "log.tag.ImsConfig WARN"
        "log.tag.ImsMultiEndpoint WARN"
        "log.tag.ImsResolver WARN"
        "log.tag.ImsUt WARN"
        "log.tag.InputFilter WARN"
        "log.tag.InputStage WARN"
        "log.tag.IntentFirewall WARN"
        "log.tag.JobStore WARN"
        "log.tag.LauncherApps WARN"
        "log.tag.LockSettingsService WARN"
        "log.tag.MmsService WARN"
        "log.tag.MountServiceIdler WARN"
        "log.tag.MtkEccNumber WARN"
        "log.tag.MtkImsConfig WARN"
        "log.tag.MtkRadio WARN"
        "log.tag.MtkRilOp WARN"
         "log.tag.NetworkPolicyManager WARN"
        "log.tag.NetworkScoreService WARN"
        "log.tag.NsdService WARN"
        "log.tag.PackageDexOptimizer WARN"
        "log.tag.PackageManagerService WARN"
        "log.tag.PermissionManager WARN"
        "log.tag.PhoneInterfaceManager WARN"
        "log.tag.PhoneStateListener WARN"
        "log.tag.PowerProfile WARN"
        "log.tag.ProcessCpuTracker WARN"
        "log.tag.ProcStatsService WARN"
        "log.tag.RestrictionsManager WARN"
        "log.tag.RoleManagerService WARN"
        "log.tag.SmsApplication WARN"
        "log.tag.SmsManager WARN"
        "log.tag.SmsStorageMonitor WARN"
        "log.tag.SoundTriggerService WARN"
        "log.tag.StatsCompanionService WARN"
        "log.tag.StorageManagerService WARN"
        "log.tag.SystemClock WARN"
        "log.tag.SystemConfig WARN"
        "log.tag.SystemServiceManager WARN"
        "log.tag.TelephonyConnectionService WARN"
        "log.tag.ThermalService WARN"
        "log.tag.TvInputManager WARN"
        "log.tag.TvInteractiveAppManager WARN"
        "log.tag.UiModeManager WARN"
        "log.tag.UpdateLock WARN"
        "log.tag.UsageStatsService WARN"
        "log.tag.UserManagerService WARN"
        "log.tag.Vold WARN"
        "log.tag.WifiAwareService WARN"
        "log.tag.WifiConfigStore WARN"
        "log.tag.WifiController WARN"
        "log.tag.WifiNetworkFactory WARN"
        "log.tag.WifiP2pService WARN"
        "log.tag.WifiScanningService WARN"
        "log.tag.WifiService WARN"
        "log.tag.WindowAnimator WARN"
        "log.tag.WindowState WARN"
        "log.tag.Zygote WARN"
        "log.tag.AnrManager WARN"
        "log.tag.AppStandbyController WARN"
        "log.tag.AppTimeLimitController WARN"
        "log.tag.BackgroundDexOptService WARN"
        "log.tag.BatterySaverController WARN"
        "log.tag.BatteryStatsHelper WARN"
        "log.tag.BinderCleaner WARN"
        "log.tag.BluetoothLeScanner WARN"
        "log.tag.BluetoothProfileService WARN"
        "log.tag.CachedDeviceState WARN"
        "log.tag.CarrierConfigLoader WARN"
        "log.tag.CdmaCallTracker WARN"
        "log.tag.ClientLifecycleManager WARN"
        "log.tag.CompanionDeviceManager WARN"
        "log.tag.CompatChanges WARN"
        "log.tag.ConnectivityMetricsLogger WARN"
        "log.tag.CpuStats WARN"
        "log.tag.CrossProfileApps WARN"
        "log.tag.DeviceConfig WARN"
        "log.tag.DeviceIdleJobsController WARN"
        "log.tag.DeviceStateManager WARN"
        "log.tag.DiskStatsService WARN"
        "log.tag.DynamicSystemService WARN"
        "log.tag.EntropyService WARN"
        "log.tag.EventDataCollector WARN"
        "log.tag.FaceService WARN"
        "log.tag.FileIntegrityService WARN"
        "log.tag.FontManagerService WARN"
        "log.tag.GameManagerService WARN"
        "log.tag.GestureLauncherService WARN"
        "log.tag.GnssNetworkConnectivityHandler WARN"
        "log.tag.GraphicsStatsService WARN"
        "log.tag.HdmiCecService WARN"
        "log.tag.ImsMediaController WARN"
        "log.tag.InputMethodService WARN"
        "log.tag.JobSchedulerService WARN"
        "log.tag.LightsManager WARN"
        "log.tag.LocationPolicy WARN"
        "log.tag.LockGuard WARN"
        "log.tag.MediaCodecService WARN"
        "log.tag.MediaCommunicationService WARN"
        "log.tag.MediaMetricsManager WARN"
        "log.tag.MediaProjectionService WARN"
        "log.tag.MediaResourceMonitor WARN"
        "log.tag.MediaRouterService WARN"
        "log.tag.MediaSessionService WARN"
        "log.tag.MmsStorage WARN"
        "log.tag.ModuleMetadataProvider WARN"
        "log.tag.MtkCarrierConfig WARN"
        "log.tag.MtkDataConnection WARN"
        "log.tag.MtkDcTracker WARN"
        "log.tag.MtkNetworkPolicy WARN"
        "log.tag.MtkServiceStateTracker WARN"
        "log.tag.MtkSignalStrength WARN"
        "log.tag.MtkTelephony WARN"
        "log.tag.NetworkAgent WARN"
        "log.tag.NetworkMonitor WARN"
        "log.tag.NetworkScoreCache WARN"
        "log.tag.OemLockService WARN"
        "log.tag.OtaDexoptService WARN"
        "log.tag.PackageInstallerSession WARN"
        "log.tag.PackageWatchdog WARN"
        "log.tag.PermissionChecker WARN"
        "log.tag.PhoneNumberGeoUtil WARN"
        "log.tag.PowerStatsService WARN"
        "log.tag.ProcessInfoService WARN"
        "log.tag.ProcessObserver WARN"
        "log.tag.RestrictedLockUtils WARN"
        "log.tag.RoleControllerService WARN"
        "log.tag.RotationLockController WARN"
        "log.tag.RuntimeService WARN"
        "log.tag.SchedulingPolicyService WARN"
        "log.tag.SensorPrivacyService WARN"
        "log.tag.SensorService WARN"
        "log.tag.ShortcutService WARN"
        "log.tag.SmartspaceService WARN"
        "log.tag.SoundTriggerMiddleware WARN"
        "log.tag.StatsManager WARN"
        "log.tag.StorageSessionController WARN"
        "log.tag.SystemBackupAgent WARN"
        "log.tag.SystemUpdateService WARN"
        "log.tag.TaskSnapshotPersister WARN"
        "log.tag.TelecomService WARN"
        "log.tag.TetheringManager WARN"
        "log.tag.TextServicesManager WARN"
        "log.tag.ThermalEventListener WARN"
        "log.tag.TimeZoneRulesManager WARN"
        "log.tag.TombstoneService WARN"
        "log.tag.TvInputHal WARN"
        "log.tag.UiModeManagerService WARN"
        "log.tag.UsageEvents WARN"
        "log.tag.UserHandle WARN"
        "log.tag.VpnProfileStore WARN"
        "log.tag.WifiAwareManager WARN"
        "log.tag.WifiBackupRestore WARN"
        "log.tag.WifiCountryCode WARN"
        "log.tag.WifiP2pManager WARN"
        "log.tag.WifiStateMachine WARN"
        "log.tag.WindowManagerShell WARN"
        "log.tag.WirelessCharger WARN"
        "log.tag.AppPredictionService WARN"
        "log.tag.ArtManagerService WARN"
        "log.tag.AudioFocus WARN"
        "log.tag.BatteryHealthService WARN"
        "log.tag.BluetoothLeAdvertiser WARN"
        "log.tag.BugreportManager WARN"
        "log.tag.CachedAppOptimizer WARN"
        "log.tag.CarrierIdentifier WARN"
        "log.tag.CdmaCallOptions WARN"
        "log.tag.ClipboardService WARN"
        "log.tag.ContentCaptureService WARN"
        "log.tag.CpuInfoService WARN"
        "log.tag.DataConnectionTracker WARN"
        "log.tag.DeviceConfigService WARN"
        "log.tag.DeviceParametersService WARN"
        "log.tag.DisplayWindowSettings WARN"
        "log.tag.EntropyRandomization WARN"
        "log.tag.ExternalStorageService WARN"
        "log.tag.FileSystemControl WARN"
        "log.tag.GnssBatchingService WARN"
        "log.tag.GnssGeofenceProxy WARN"
        "log.tag.GnssNavigationMessage WARN"
        "log.tag.HdmiAudioService WARN"
        "log.tag.InputEventReceiver WARN"
        "log.tag.JobCompletionService WARN"
        "log.tag.LauncherAppsService WARN"
        "log.tag.LockSettingsStorage WARN"
        "log.tag.MediaDrmService WARN"
        "log.tag.MediaExtractorService WARN"
        "log.tag.MediaTranscodingService WARN"
        "log.tag.MmsSendReceive WARN"
        "log.tag.MtkCallManager WARN"
        "log.tag.MtkNetworkAgent WARN"
        "log.tag.MtkRilClient WARN"
        "log.tag.NetworkTimeService WARN"
        "log.tag.PackageParser WARN"
        "log.tag.PermissionManagerService WARN"
        "log.tag.PhoneNumberUtils WARN"
        "log.tag.ProcessRecord WARN"
        "log.tag.SmsBroadcastProxy WARN"
        "log.tag.SoundTriggerHwService WARN"
        "log.tag.SystemCompanionService WARN"
        "log.tag.TetheringInterface WARN"
        "log.tag.TvInputService WARN"
        "log.tag.UserSetupComplete WARN"
        "log.tag.VpnService WARN"
        "log.tag.WifiConfigManager WARN"
        "log.tag.WifiMonitor WARN"
        "log.tag.WifiVendorHal WARN"
        "log.tag.WindowSurfaceController WARN"
        "log.tag.ActivityStackSupervisor WARN"
        "log.tag.AppStandbyBucket WARN"
        "log.tag.BatterySaverPolicy WARN"
        "log.tag.BluetoothHealth WARN"
        "log.tag.BroadcastStats WARN"
        "log.tag.CdmaConnection WARN"
        "log.tag.CompatConfig WARN"
        "log.tag.ConnectivityResources WARN"
        "log.tag.DeviceIdleManager WARN"
        "log.tag.DevicePolicyEngine WARN"
        "log.tag.DisplayPowerController WARN"
        "log.tag.GnssMeasurementsProvider WARN"
        "log.tag.ImsPhoneCallTracker WARN"
        "log.tag.InputTransport WARN"
        "log.tag.JobHandler WARN"
        "log.tag.LightsService WARN"
        "log.tag.LocationPolicyService WARN"
        "log.tag.MmsNetworkManager WARN"
        "log.tag.MtkImsCallSession WARN"
        "log.tag.MtkPhoneFactory WARN"
        "log.tag.NetworkStatsService WARN"
        "log.tag.PackageVerifier WARN"
        "log.tag.PhoneSwitcher WARN"
        "log.tag.ProcessStatsService WARN"
        "log.tag.RestrictionsProvider WARN"
        "log.tag.SmsController WARN"
        "log.tag.SmsStorageService WARN"
        "log.tag.SystemConfigService WARN"
        "log.tag.ThermalPolicy WARN"
        "log.tag.UiccPhoneBookController WARN"
        "log.tag.UserManager WARN"
        "log.tag.WifiActiveModeManager WARN"
        "log.tag.WifiP2pMonitor WARN"
        "log.tag.WifiThreadRunner WARN"
        "log.tag.AppIdleHistory WARN"
        "log.tag.BatteryUsageStats WARN"
        "log.tag.BluetoothLeBroadcast WARN"
        "log.tag.CdmaServiceCategory WARN"
        "log.tag.ConnectivityDiagnostics WARN"
        "log.tag.DeviceActivityController WARN"
        "log.tag.DisplayPowerState WARN"
        "log.tag.GnssStatusProvider WARN"
        "log.tag.InputMethodClient WARN"
        "log.tag.JobConcurrencyManager WARN"
        "log.tag.MmsRequestManager WARN"
        "log.tag.MtkDataNetwork WARN"
        "log.tag.MtkRadioInterface WARN"
        "log.tag.NetworkAgentInfo WARN"
        "log.tag.PackageManagerShell WARN"
        "log.tag.PhoneConfigurationManager WARN"
        "log.tag.SmsMessageBase WARN"
        "log.tag.ThermalStatusListener WARN"
        "log.tag.WifiClientModeManager WARN"
        "log.tag.WifiConfigStore WARN"
        "log.tag.WifiNetworkAgent WARN"
        "log.tag.ActivityRecognition WARN"
        "log.tag.AppPredictionManager WARN"
        "log.tag.BatteryStatsValidator WARN"
        "log.tag.BluetoothLeAudio WARN"
        "log.tag.CdmaInboundSmsHandler WARN"
        "log.tag.DeviceStateMonitor WARN"
        "log.tag.GnssVisibilityControl WARN"
        "log.tag.ImsCallForward WARN"
        "log.tag.MtkImsUt WARN"
        "log.tag.NetworkPolicyCallback WARN"
        "log.tag.PackageInstallerService WARN"
        "log.tag.SmsBroadcastUndelivered WARN"
        "log.tag.ThermalEventHandler WARN"
        "log.tag.WifiAwareStateManager WARN"
        "log.tag.WifiP2pDeviceList WARN"
        "log.tag.AppStandbyState WARN"
        "log.tag.BatterySaverStateMachine WARN"
        "log.tag.BluetoothLeCallControl WARN"
        "log.tag.CdmaServiceProvider WARN"
        "log.tag.DeviceConfigProxy WARN"
        "log.tag.GnssTimeUpdateService WARN"
        "log.tag.MtkNetworkStats WARN"
        "log.tag.PackageStateModule WARN"
        "log.tag.SmsInboundHandler WARN"
        "log.tag.WifiP2pGroup WARN"
        "log.tag.ActivityTrigger WARN"
        "log.tag.BluetoothLeAudioCodec WARN"
        "log.tag.CdmaSmsBroadcast WARN"
        "log.tag.MtkImsMedia WARN"
        "log.tag.NetworkStatsCollection WARN"
        "log.tag.SmsMessageRecord WARN"
        "log.tag.WifiP2pServiceImpl WARN"
        "log.tag.AppStandbyTracker WARN"
        "log.tag.BatterySaverSchedule WARN"
        "log.tag.MtkRilSocket WARN"
        "log.tag.WifiP2pNative WARN"
        "log.tag.BluetoothLeAudioProfile WARN"
        "log.tag.MtkImsRegistration WARN"
        "log.tag.SmsMessageSender WARN"
        "log.tag.WifiP2pConfig WARN"
        "log.tag.MtkRilRequest WARN"
        "log.tag.BluetoothLeAudioBroadcast WARN"
        "log.tag.SmsMessageStorage WARN"
        "log.tag.WifiP2pDiscovery WARN"
        "log.tag.MtkImsEmergency WARN"
        "log.tag.WifiP2pConnection WARN"
        "log.tag.MtkRilResponse WARN"
        "log.tag.WifiP2pMonitorImpl WARN"
        "log.tag.MtkImsFeature WARN"
        "log.tag.WifiP2pPeer WARN"
    )
}

    for cmd in "${log_tags[@]}"; do
        IFS=' ' read -r name value <<< "$cmd"
        setprop "$name" "$value" 2>>"$log_file"
    done
    echo "[+] Log Suppression Applied (700 tags)"

apply_optimizations() {
    print_progress "Applying Ultra Touch Sensitivity"
    touch_settings=(
        "touch.size.calibration none"
        "touch.pressure.calibration none"
        "touch.distance.calibration none"
        "touch.gestureMode pointer"
        "touch.orientationAware 1"
        "touch.deviceType touchScreen"
        "touch.tap.interval 40"
        "touch.doubletap.interval 120"
        "touch.scroll.sensitivity 1.8"
        "touch.fling.velocity 1.2"
    )

    print_progress "Applying Graphics Boost"
    graphics_settings=(
        "debug.sf.hw 1"
        "debug.egl.hw 1"
        "debug.sf.enable_gl_backpressure 0"
        "debug.sf.latch_unsignaled 1"
        "debug.sf.enable_hwc_vds 1"
        "debug.sf.predict_hwc_composition_strategy true"
        "debug.hwui.use_hint_manager true"
        "debug.hwui.use_buffer_age 1"
        "debug.renderengine.backend skiagputhreaded"
        "debug.sf.use_phase_offsets_as_durations true"
        "debug.sf.early_phase_offset_ns -8333333"
        "debug.sf.early_app_phase_offset_ns -8333333"
        "debug.sf.early_gl_phase_offset_ns -8333333"
        "debug.sf.high_fps_early_phase_offset_ns -8333333"
        "debug.sf.frame_rate_multiple 2"
        "debug.hwui.overdraw none"
        "debug.hwui.target_cpu_time_percent 90"
    )

    print_progress "Applying VSync Optimization"
    vsync_settings=(
        "debug.egl.swapinterval 0"
        "debug.gr.swapinterval 0"
        "debug.sf.swapinterval 0"
    )

    print_progress "Applying Max Performance Boost"
    system_settings=(
        "low_power 0"
        "cached_apps_freezer enabled"
        "DYNAMIC_PERFORMANCE_STATUS 1"
        "game_auto_temperature 0"
        "game_dashboard_always_on 1"
        "power.performance_mode high"
    )

    print_progress "Applying Free Fire Ultra Overlay"
    game_overlay=(
        "game_overlay com.dts.freefireth mode=2,angle=true,fps=$refresh_rate,loadingBoost=999999999,priority=1,cpuHint=true,gpuHint=true"
        "game_overlay com.dts.freefiremax mode=2,angle=true,fps=$refresh_rate,loadingBoost=999999999,priority=1,cpuHint=true,gpuHint=true"
    )

    print_progress "Disabling Heavy Graphics Effects"
    disable_effects=(
        "debug.egl.force_msaa 0"
        "debug.hwui.force_fxaa 0"
        "debug.hwui.force_smaa 0"
        "debug.hwui.force_msaa 0"
        "debug.hwui.force_txaa 0"
        "debug.hwui.force_csaa 0"
        "log.tag.WifiP2pPeer WARN"
        "debug.hwui.force_dlss 0"
    )

    print_progress "Stopping Background Services"
    background_services=(
        "com.samsung.android.game.gos"
        "com.xiaomi.joyose"
        "com.google.android.gms"
    )

    for cmd in "${touch_settings[@]}"; do
        IFS=' ' read -r key value <<< "$cmd"
        settings put system "$key" "$value" 2>>"$log_file"
    done
    echo "[+] Ultra Touch Sensitivity Applied"

    for cmd in "${graphics_settings[@]}"; do
        IFS=' ' read -r key value <<< "$cmd"
        setprop "$key" "$value" 2>>"$log_file"
    done
    echo "[+] Graphics Boost Applied"

    for cmd in "${vsync_settings[@]}"; do
        IFS=' ' read -r key value <<< "$cmd"
        setprop "$key" "$value" 2>>"$log_file"
    done
    echo "[+] VSync Optimization Applied"

    for cmd in "${system_settings[@]}"; do
        IFS=' ' read -r key value <<< "$cmd"
        settings put global "$key" "$value" 2>>"$log_file"
    done
    echo "[+] Max Performance Boost Applied"

    for cmd in "${game_overlay[@]}"; do
        IFS=' ' read -r namespace key value <<< "$cmd"
        device_config put "$namespace" "$key" "$value" 2>>"$log_file"
    done
    echo "[+] Free Fire Ultra Overlay Applied"

    for cmd in "${disable_effects[@]}"; do
        IFS=' ' read -r key value <<< "$cmd"
        setprop "$key" "$value" 2>>"$log_file"
    done
    echo "[+] Heavy Graphics Effects Disabled"

    for service in "${background_services[@]}"; do
        stop "$service" 2>>"$log_file" || true
    done
    echo "[+] Background Services Stopped"

    print_progress "Applying Ultra Frame Timing"
    frame_ns=$(echo "1000000000 / $refresh_rate" | bc)
    early_app=$(echo "$frame_ns * 0.25" | bc)
    early_sf=$(echo "$frame_ns * 0.2" | bc)
    setprop debug.sf.early.app.duration "$early_app" 2>>"$log_file"
    setprop debug.sf.early.sf.duration "$early_sf" 2>>"$log_file"
    setprop debug.sf.early_app_phase_offset_ns "-$early_app" 2>>"$log_file"
    setprop debug.sf.early_phase_offset_ns "-$early_sf" 2>>"$log_file"
    echo "[+] Ultra Frame Timing Applied"

    print_progress "Clearing Logcat Buffer"
    logcat -G 96K 2>>"$log_file"
    logcat -c 2>>"$log_file"
    echo "[+] Logcat Buffer Cleared"
}

check_compatibility
log
apply_optimizations

echo "╔══════════════════════════════════════════════════════════════╗"
echo "║          Sensi PlusX V2 Completed                            ║"
echo "╠══════════════════════════════════════════════════════════════╩╗"
echo "║ [*] Script executed successfully on $(date '+%Y-%m-%d %H:%M:%S') ║"
echo "║ [*] Thank you for using Sensi PlusX V2!                    ║"
echo "║ [*] Author: Kysertweaks | Country: VietNam 🇻🇳            ║"
echo "╚══════════════════════════════════════════════════════════════╝"
        
